/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * Rolling update config params. Present only if MachineDeploymentStrategyType &#x3D; RollingUpdate.
 */
@ApiModel(description = "Rolling update config params. Present only if MachineDeploymentStrategyType = RollingUpdate.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate {
  /**
   * DeletePolicy defines the policy used by the MachineDeployment to identify nodes to delete when downscaling. Valid values are \&quot;Random, \&quot;Newest\&quot;, \&quot;Oldest\&quot; When no value is supplied, the default DeletePolicy of MachineSet is used
   */
  @JsonAdapter(DeletePolicyEnum.Adapter.class)
  public enum DeletePolicyEnum {
    RANDOM("Random"),
    
    NEWEST("Newest"),
    
    OLDEST("Oldest");

    private String value;

    DeletePolicyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DeletePolicyEnum fromValue(String value) {
      for (DeletePolicyEnum b : DeletePolicyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DeletePolicyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DeletePolicyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DeletePolicyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DeletePolicyEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DeletePolicyEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DELETE_POLICY = "deletePolicy";
  @SerializedName(SERIALIZED_NAME_DELETE_POLICY)
  private DeletePolicyEnum deletePolicy;

  public static final String SERIALIZED_NAME_MAX_SURGE = "maxSurge";
  @SerializedName(SERIALIZED_NAME_MAX_SURGE)
  private Object maxSurge;

  public static final String SERIALIZED_NAME_MAX_UNAVAILABLE = "maxUnavailable";
  @SerializedName(SERIALIZED_NAME_MAX_UNAVAILABLE)
  private Object maxUnavailable;

  public V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate() {
  }

  public V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate deletePolicy(DeletePolicyEnum deletePolicy) {
    this.deletePolicy = deletePolicy;
    return this;
  }

   /**
   * DeletePolicy defines the policy used by the MachineDeployment to identify nodes to delete when downscaling. Valid values are \&quot;Random, \&quot;Newest\&quot;, \&quot;Oldest\&quot; When no value is supplied, the default DeletePolicy of MachineSet is used
   * @return deletePolicy
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "DeletePolicy defines the policy used by the MachineDeployment to identify nodes to delete when downscaling. Valid values are \"Random, \"Newest\", \"Oldest\" When no value is supplied, the default DeletePolicy of MachineSet is used")
  public DeletePolicyEnum getDeletePolicy() {
    return deletePolicy;
  }

  public void setDeletePolicy(DeletePolicyEnum deletePolicy) {
    this.deletePolicy = deletePolicy;
  }


  public V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate maxSurge(Object maxSurge) {
    this.maxSurge = maxSurge;
    return this;
  }

   /**
   * The maximum number of machines that can be scheduled above the desired number of machines. Value can be an absolute number (ex: 5) or a percentage of desired machines (ex: 10%). This can not be 0 if MaxUnavailable is 0. Absolute number is calculated from percentage by rounding up. Defaults to 1. Example: when this is set to 30%, the new MachineSet can be scaled up immediately when the rolling update starts, such that the total number of old and new machines do not exceed 130% of desired machines. Once old machines have been killed, new MachineSet can be scaled up further, ensuring that total number of machines running at any time during the update is at most 130% of desired machines.
   * @return maxSurge
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "The maximum number of machines that can be scheduled above the desired number of machines. Value can be an absolute number (ex: 5) or a percentage of desired machines (ex: 10%). This can not be 0 if MaxUnavailable is 0. Absolute number is calculated from percentage by rounding up. Defaults to 1. Example: when this is set to 30%, the new MachineSet can be scaled up immediately when the rolling update starts, such that the total number of old and new machines do not exceed 130% of desired machines. Once old machines have been killed, new MachineSet can be scaled up further, ensuring that total number of machines running at any time during the update is at most 130% of desired machines.")
  public Object getMaxSurge() {
    return maxSurge;
  }

  public void setMaxSurge(Object maxSurge) {
    this.maxSurge = maxSurge;
  }


  public V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate maxUnavailable(Object maxUnavailable) {
    this.maxUnavailable = maxUnavailable;
    return this;
  }

   /**
   * The maximum number of machines that can be unavailable during the update. Value can be an absolute number (ex: 5) or a percentage of desired machines (ex: 10%). Absolute number is calculated from percentage by rounding down. This can not be 0 if MaxSurge is 0. Defaults to 0. Example: when this is set to 30%, the old MachineSet can be scaled down to 70% of desired machines immediately when the rolling update starts. Once new machines are ready, old MachineSet can be scaled down further, followed by scaling up the new MachineSet, ensuring that the total number of machines available at all times during the update is at least 70% of desired machines.
   * @return maxUnavailable
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "The maximum number of machines that can be unavailable during the update. Value can be an absolute number (ex: 5) or a percentage of desired machines (ex: 10%). Absolute number is calculated from percentage by rounding down. This can not be 0 if MaxSurge is 0. Defaults to 0. Example: when this is set to 30%, the old MachineSet can be scaled down to 70% of desired machines immediately when the rolling update starts. Once new machines are ready, old MachineSet can be scaled down further, followed by scaling up the new MachineSet, ensuring that the total number of machines available at all times during the update is at least 70% of desired machines.")
  public Object getMaxUnavailable() {
    return maxUnavailable;
  }

  public void setMaxUnavailable(Object maxUnavailable) {
    this.maxUnavailable = maxUnavailable;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate v1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate = (V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate) o;
    return Objects.equals(this.deletePolicy, v1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate.deletePolicy) &&
        Objects.equals(this.maxSurge, v1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate.maxSurge) &&
        Objects.equals(this.maxUnavailable, v1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate.maxUnavailable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deletePolicy, maxSurge, maxUnavailable);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate {\n");
    sb.append("    deletePolicy: ").append(toIndentedString(deletePolicy)).append("\n");
    sb.append("    maxSurge: ").append(toIndentedString(maxSurge)).append("\n");
    sb.append("    maxUnavailable: ").append(toIndentedString(maxUnavailable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("deletePolicy");
    openapiFields.add("maxSurge");
    openapiFields.add("maxUnavailable");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate is not found in the empty JSON string", V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("deletePolicy") != null && !jsonObj.get("deletePolicy").isJsonNull()) && !jsonObj.get("deletePolicy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deletePolicy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deletePolicy").toString()));
      }
      // validate the optional field `deletePolicy`
      if (jsonObj.get("deletePolicy") != null && !jsonObj.get("deletePolicy").isJsonNull()) {
        DeletePolicyEnum.validateJsonElement(jsonObj.get("deletePolicy"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate
  */
  public static V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate.class);
  }

 /**
  * Convert an instance of V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRollingUpdate to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

