/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.x_k8s.cluster.models.V1beta1ClusterSpecTopologyWorkersMachinePoolsInnerMetadata;
import io.x_k8s.cluster.models.V1beta1ClusterSpecTopologyWorkersMachinePoolsInnerVariables;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * MachinePoolTopology specifies the different parameters for a pool of worker nodes in the topology. This pool of nodes is managed by a MachinePool object whose lifecycle is managed by the Cluster controller.
 */
@ApiModel(description = "MachinePoolTopology specifies the different parameters for a pool of worker nodes in the topology. This pool of nodes is managed by a MachinePool object whose lifecycle is managed by the Cluster controller.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterSpecTopologyWorkersMachinePoolsInner {
  public static final String SERIALIZED_NAME_PROPERTY_CLASS = "class";
  @SerializedName(SERIALIZED_NAME_PROPERTY_CLASS)
  private String propertyClass;

  public static final String SERIALIZED_NAME_FAILURE_DOMAINS = "failureDomains";
  @SerializedName(SERIALIZED_NAME_FAILURE_DOMAINS)
  private List<String> failureDomains = new ArrayList<>();

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private V1beta1ClusterSpecTopologyWorkersMachinePoolsInnerMetadata metadata;

  public static final String SERIALIZED_NAME_MIN_READY_SECONDS = "minReadySeconds";
  @SerializedName(SERIALIZED_NAME_MIN_READY_SECONDS)
  private Integer minReadySeconds;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NODE_DELETION_TIMEOUT = "nodeDeletionTimeout";
  @SerializedName(SERIALIZED_NAME_NODE_DELETION_TIMEOUT)
  private String nodeDeletionTimeout;

  public static final String SERIALIZED_NAME_NODE_DRAIN_TIMEOUT = "nodeDrainTimeout";
  @SerializedName(SERIALIZED_NAME_NODE_DRAIN_TIMEOUT)
  private String nodeDrainTimeout;

  public static final String SERIALIZED_NAME_NODE_VOLUME_DETACH_TIMEOUT = "nodeVolumeDetachTimeout";
  @SerializedName(SERIALIZED_NAME_NODE_VOLUME_DETACH_TIMEOUT)
  private String nodeVolumeDetachTimeout;

  public static final String SERIALIZED_NAME_REPLICAS = "replicas";
  @SerializedName(SERIALIZED_NAME_REPLICAS)
  private Integer replicas;

  public static final String SERIALIZED_NAME_VARIABLES = "variables";
  @SerializedName(SERIALIZED_NAME_VARIABLES)
  private V1beta1ClusterSpecTopologyWorkersMachinePoolsInnerVariables variables;

  public V1beta1ClusterSpecTopologyWorkersMachinePoolsInner() {
  }

  public V1beta1ClusterSpecTopologyWorkersMachinePoolsInner propertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
    return this;
  }

   /**
   * Class is the name of the MachinePoolClass used to create the pool of worker nodes. This should match one of the deployment classes defined in the ClusterClass object mentioned in the &#x60;Cluster.Spec.Class&#x60; field.
   * @return propertyClass
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Class is the name of the MachinePoolClass used to create the pool of worker nodes. This should match one of the deployment classes defined in the ClusterClass object mentioned in the `Cluster.Spec.Class` field.")
  public String getPropertyClass() {
    return propertyClass;
  }

  public void setPropertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
  }


  public V1beta1ClusterSpecTopologyWorkersMachinePoolsInner failureDomains(List<String> failureDomains) {
    this.failureDomains = failureDomains;
    return this;
  }

  public V1beta1ClusterSpecTopologyWorkersMachinePoolsInner addFailureDomainsItem(String failureDomainsItem) {
    if (this.failureDomains == null) {
      this.failureDomains = new ArrayList<>();
    }
    this.failureDomains.add(failureDomainsItem);
    return this;
  }

   /**
   * FailureDomains is the list of failure domains the machine pool will be created in. Must match a key in the FailureDomains map stored on the cluster object.
   * @return failureDomains
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "FailureDomains is the list of failure domains the machine pool will be created in. Must match a key in the FailureDomains map stored on the cluster object.")
  public List<String> getFailureDomains() {
    return failureDomains;
  }

  public void setFailureDomains(List<String> failureDomains) {
    this.failureDomains = failureDomains;
  }


  public V1beta1ClusterSpecTopologyWorkersMachinePoolsInner metadata(V1beta1ClusterSpecTopologyWorkersMachinePoolsInnerMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1beta1ClusterSpecTopologyWorkersMachinePoolsInnerMetadata getMetadata() {
    return metadata;
  }

  public void setMetadata(V1beta1ClusterSpecTopologyWorkersMachinePoolsInnerMetadata metadata) {
    this.metadata = metadata;
  }


  public V1beta1ClusterSpecTopologyWorkersMachinePoolsInner minReadySeconds(Integer minReadySeconds) {
    this.minReadySeconds = minReadySeconds;
    return this;
  }

   /**
   * Minimum number of seconds for which a newly created machine pool should be ready. Defaults to 0 (machine will be considered available as soon as it is ready)
   * @return minReadySeconds
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Minimum number of seconds for which a newly created machine pool should be ready. Defaults to 0 (machine will be considered available as soon as it is ready)")
  public Integer getMinReadySeconds() {
    return minReadySeconds;
  }

  public void setMinReadySeconds(Integer minReadySeconds) {
    this.minReadySeconds = minReadySeconds;
  }


  public V1beta1ClusterSpecTopologyWorkersMachinePoolsInner name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name is the unique identifier for this MachinePoolTopology. The value is used with other unique identifiers to create a MachinePool&#39;s Name (e.g. cluster&#39;s name, etc). In case the name is greater than the allowed maximum length, the values are hashed together.
   * @return name
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Name is the unique identifier for this MachinePoolTopology. The value is used with other unique identifiers to create a MachinePool's Name (e.g. cluster's name, etc). In case the name is greater than the allowed maximum length, the values are hashed together.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public V1beta1ClusterSpecTopologyWorkersMachinePoolsInner nodeDeletionTimeout(String nodeDeletionTimeout) {
    this.nodeDeletionTimeout = nodeDeletionTimeout;
    return this;
  }

   /**
   * NodeDeletionTimeout defines how long the controller will attempt to delete the Node that the MachinePool hosts after the MachinePool is marked for deletion. A duration of 0 will retry deletion indefinitely. Defaults to 10 seconds.
   * @return nodeDeletionTimeout
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "NodeDeletionTimeout defines how long the controller will attempt to delete the Node that the MachinePool hosts after the MachinePool is marked for deletion. A duration of 0 will retry deletion indefinitely. Defaults to 10 seconds.")
  public String getNodeDeletionTimeout() {
    return nodeDeletionTimeout;
  }

  public void setNodeDeletionTimeout(String nodeDeletionTimeout) {
    this.nodeDeletionTimeout = nodeDeletionTimeout;
  }


  public V1beta1ClusterSpecTopologyWorkersMachinePoolsInner nodeDrainTimeout(String nodeDrainTimeout) {
    this.nodeDrainTimeout = nodeDrainTimeout;
    return this;
  }

   /**
   * NodeDrainTimeout is the total amount of time that the controller will spend on draining a node. The default value is 0, meaning that the node can be drained without any time limitations. NOTE: NodeDrainTimeout is different from &#x60;kubectl drain --timeout&#x60;
   * @return nodeDrainTimeout
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "NodeDrainTimeout is the total amount of time that the controller will spend on draining a node. The default value is 0, meaning that the node can be drained without any time limitations. NOTE: NodeDrainTimeout is different from `kubectl drain --timeout`")
  public String getNodeDrainTimeout() {
    return nodeDrainTimeout;
  }

  public void setNodeDrainTimeout(String nodeDrainTimeout) {
    this.nodeDrainTimeout = nodeDrainTimeout;
  }


  public V1beta1ClusterSpecTopologyWorkersMachinePoolsInner nodeVolumeDetachTimeout(String nodeVolumeDetachTimeout) {
    this.nodeVolumeDetachTimeout = nodeVolumeDetachTimeout;
    return this;
  }

   /**
   * NodeVolumeDetachTimeout is the total amount of time that the controller will spend on waiting for all volumes to be detached. The default value is 0, meaning that the volumes can be detached without any time limitations.
   * @return nodeVolumeDetachTimeout
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "NodeVolumeDetachTimeout is the total amount of time that the controller will spend on waiting for all volumes to be detached. The default value is 0, meaning that the volumes can be detached without any time limitations.")
  public String getNodeVolumeDetachTimeout() {
    return nodeVolumeDetachTimeout;
  }

  public void setNodeVolumeDetachTimeout(String nodeVolumeDetachTimeout) {
    this.nodeVolumeDetachTimeout = nodeVolumeDetachTimeout;
  }


  public V1beta1ClusterSpecTopologyWorkersMachinePoolsInner replicas(Integer replicas) {
    this.replicas = replicas;
    return this;
  }

   /**
   * Replicas is the number of nodes belonging to this pool. If the value is nil, the MachinePool is created without the number of Replicas (defaulting to 1) and it&#39;s assumed that an external entity (like cluster autoscaler) is responsible for the management of this value.
   * @return replicas
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Replicas is the number of nodes belonging to this pool. If the value is nil, the MachinePool is created without the number of Replicas (defaulting to 1) and it's assumed that an external entity (like cluster autoscaler) is responsible for the management of this value.")
  public Integer getReplicas() {
    return replicas;
  }

  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }


  public V1beta1ClusterSpecTopologyWorkersMachinePoolsInner variables(V1beta1ClusterSpecTopologyWorkersMachinePoolsInnerVariables variables) {
    this.variables = variables;
    return this;
  }

   /**
   * Get variables
   * @return variables
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1beta1ClusterSpecTopologyWorkersMachinePoolsInnerVariables getVariables() {
    return variables;
  }

  public void setVariables(V1beta1ClusterSpecTopologyWorkersMachinePoolsInnerVariables variables) {
    this.variables = variables;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterSpecTopologyWorkersMachinePoolsInner v1beta1ClusterSpecTopologyWorkersMachinePoolsInner = (V1beta1ClusterSpecTopologyWorkersMachinePoolsInner) o;
    return Objects.equals(this.propertyClass, v1beta1ClusterSpecTopologyWorkersMachinePoolsInner.propertyClass) &&
        Objects.equals(this.failureDomains, v1beta1ClusterSpecTopologyWorkersMachinePoolsInner.failureDomains) &&
        Objects.equals(this.metadata, v1beta1ClusterSpecTopologyWorkersMachinePoolsInner.metadata) &&
        Objects.equals(this.minReadySeconds, v1beta1ClusterSpecTopologyWorkersMachinePoolsInner.minReadySeconds) &&
        Objects.equals(this.name, v1beta1ClusterSpecTopologyWorkersMachinePoolsInner.name) &&
        Objects.equals(this.nodeDeletionTimeout, v1beta1ClusterSpecTopologyWorkersMachinePoolsInner.nodeDeletionTimeout) &&
        Objects.equals(this.nodeDrainTimeout, v1beta1ClusterSpecTopologyWorkersMachinePoolsInner.nodeDrainTimeout) &&
        Objects.equals(this.nodeVolumeDetachTimeout, v1beta1ClusterSpecTopologyWorkersMachinePoolsInner.nodeVolumeDetachTimeout) &&
        Objects.equals(this.replicas, v1beta1ClusterSpecTopologyWorkersMachinePoolsInner.replicas) &&
        Objects.equals(this.variables, v1beta1ClusterSpecTopologyWorkersMachinePoolsInner.variables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyClass, failureDomains, metadata, minReadySeconds, name, nodeDeletionTimeout, nodeDrainTimeout, nodeVolumeDetachTimeout, replicas, variables);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterSpecTopologyWorkersMachinePoolsInner {\n");
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("    failureDomains: ").append(toIndentedString(failureDomains)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    minReadySeconds: ").append(toIndentedString(minReadySeconds)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nodeDeletionTimeout: ").append(toIndentedString(nodeDeletionTimeout)).append("\n");
    sb.append("    nodeDrainTimeout: ").append(toIndentedString(nodeDrainTimeout)).append("\n");
    sb.append("    nodeVolumeDetachTimeout: ").append(toIndentedString(nodeVolumeDetachTimeout)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("class");
    openapiFields.add("failureDomains");
    openapiFields.add("metadata");
    openapiFields.add("minReadySeconds");
    openapiFields.add("name");
    openapiFields.add("nodeDeletionTimeout");
    openapiFields.add("nodeDrainTimeout");
    openapiFields.add("nodeVolumeDetachTimeout");
    openapiFields.add("replicas");
    openapiFields.add("variables");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("class");
    openapiRequiredFields.add("name");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterSpecTopologyWorkersMachinePoolsInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterSpecTopologyWorkersMachinePoolsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterSpecTopologyWorkersMachinePoolsInner is not found in the empty JSON string", V1beta1ClusterSpecTopologyWorkersMachinePoolsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterSpecTopologyWorkersMachinePoolsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterSpecTopologyWorkersMachinePoolsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1beta1ClusterSpecTopologyWorkersMachinePoolsInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("class").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `class` to be a primitive type in the JSON string but got `%s`", jsonObj.get("class").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("failureDomains") != null && !jsonObj.get("failureDomains").isJsonNull() && !jsonObj.get("failureDomains").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `failureDomains` to be an array in the JSON string but got `%s`", jsonObj.get("failureDomains").toString()));
      }
      // validate the optional field `metadata`
      if (jsonObj.get("metadata") != null && !jsonObj.get("metadata").isJsonNull()) {
        V1beta1ClusterSpecTopologyWorkersMachinePoolsInnerMetadata.validateJsonElement(jsonObj.get("metadata"));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("nodeDeletionTimeout") != null && !jsonObj.get("nodeDeletionTimeout").isJsonNull()) && !jsonObj.get("nodeDeletionTimeout").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nodeDeletionTimeout` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nodeDeletionTimeout").toString()));
      }
      if ((jsonObj.get("nodeDrainTimeout") != null && !jsonObj.get("nodeDrainTimeout").isJsonNull()) && !jsonObj.get("nodeDrainTimeout").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nodeDrainTimeout` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nodeDrainTimeout").toString()));
      }
      if ((jsonObj.get("nodeVolumeDetachTimeout") != null && !jsonObj.get("nodeVolumeDetachTimeout").isJsonNull()) && !jsonObj.get("nodeVolumeDetachTimeout").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nodeVolumeDetachTimeout` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nodeVolumeDetachTimeout").toString()));
      }
      // validate the optional field `variables`
      if (jsonObj.get("variables") != null && !jsonObj.get("variables").isJsonNull()) {
        V1beta1ClusterSpecTopologyWorkersMachinePoolsInnerVariables.validateJsonElement(jsonObj.get("variables"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterSpecTopologyWorkersMachinePoolsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterSpecTopologyWorkersMachinePoolsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterSpecTopologyWorkersMachinePoolsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterSpecTopologyWorkersMachinePoolsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterSpecTopologyWorkersMachinePoolsInner>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterSpecTopologyWorkersMachinePoolsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterSpecTopologyWorkersMachinePoolsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterSpecTopologyWorkersMachinePoolsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterSpecTopologyWorkersMachinePoolsInner
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterSpecTopologyWorkersMachinePoolsInner
  */
  public static V1beta1ClusterSpecTopologyWorkersMachinePoolsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterSpecTopologyWorkersMachinePoolsInner.class);
  }

 /**
  * Convert an instance of V1beta1ClusterSpecTopologyWorkersMachinePoolsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

