/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.x_k8s.cluster.models.V1beta1ClusterResourceSetBindingSpecBindingsInnerResourcesInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * ResourceSetBinding keeps info on all of the resources in a ClusterResourceSet.
 */
@ApiModel(description = "ResourceSetBinding keeps info on all of the resources in a ClusterResourceSet.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterResourceSetBindingSpecBindingsInner {
  public static final String SERIALIZED_NAME_CLUSTER_RESOURCE_SET_NAME = "clusterResourceSetName";
  @SerializedName(SERIALIZED_NAME_CLUSTER_RESOURCE_SET_NAME)
  private String clusterResourceSetName;

  public static final String SERIALIZED_NAME_RESOURCES = "resources";
  @SerializedName(SERIALIZED_NAME_RESOURCES)
  private List<V1beta1ClusterResourceSetBindingSpecBindingsInnerResourcesInner> resources = new ArrayList<>();

  public V1beta1ClusterResourceSetBindingSpecBindingsInner() {
  }

  public V1beta1ClusterResourceSetBindingSpecBindingsInner clusterResourceSetName(String clusterResourceSetName) {
    this.clusterResourceSetName = clusterResourceSetName;
    return this;
  }

   /**
   * ClusterResourceSetName is the name of the ClusterResourceSet that is applied to the owner cluster of the binding.
   * @return clusterResourceSetName
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "ClusterResourceSetName is the name of the ClusterResourceSet that is applied to the owner cluster of the binding.")
  public String getClusterResourceSetName() {
    return clusterResourceSetName;
  }

  public void setClusterResourceSetName(String clusterResourceSetName) {
    this.clusterResourceSetName = clusterResourceSetName;
  }


  public V1beta1ClusterResourceSetBindingSpecBindingsInner resources(List<V1beta1ClusterResourceSetBindingSpecBindingsInnerResourcesInner> resources) {
    this.resources = resources;
    return this;
  }

  public V1beta1ClusterResourceSetBindingSpecBindingsInner addResourcesItem(V1beta1ClusterResourceSetBindingSpecBindingsInnerResourcesInner resourcesItem) {
    if (this.resources == null) {
      this.resources = new ArrayList<>();
    }
    this.resources.add(resourcesItem);
    return this;
  }

   /**
   * Resources is a list of resources that the ClusterResourceSet has.
   * @return resources
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Resources is a list of resources that the ClusterResourceSet has.")
  public List<V1beta1ClusterResourceSetBindingSpecBindingsInnerResourcesInner> getResources() {
    return resources;
  }

  public void setResources(List<V1beta1ClusterResourceSetBindingSpecBindingsInnerResourcesInner> resources) {
    this.resources = resources;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterResourceSetBindingSpecBindingsInner v1beta1ClusterResourceSetBindingSpecBindingsInner = (V1beta1ClusterResourceSetBindingSpecBindingsInner) o;
    return Objects.equals(this.clusterResourceSetName, v1beta1ClusterResourceSetBindingSpecBindingsInner.clusterResourceSetName) &&
        Objects.equals(this.resources, v1beta1ClusterResourceSetBindingSpecBindingsInner.resources);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clusterResourceSetName, resources);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterResourceSetBindingSpecBindingsInner {\n");
    sb.append("    clusterResourceSetName: ").append(toIndentedString(clusterResourceSetName)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("clusterResourceSetName");
    openapiFields.add("resources");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("clusterResourceSetName");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterResourceSetBindingSpecBindingsInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterResourceSetBindingSpecBindingsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterResourceSetBindingSpecBindingsInner is not found in the empty JSON string", V1beta1ClusterResourceSetBindingSpecBindingsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterResourceSetBindingSpecBindingsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterResourceSetBindingSpecBindingsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1beta1ClusterResourceSetBindingSpecBindingsInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("clusterResourceSetName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clusterResourceSetName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clusterResourceSetName").toString()));
      }
      if (jsonObj.get("resources") != null && !jsonObj.get("resources").isJsonNull()) {
        JsonArray jsonArrayresources = jsonObj.getAsJsonArray("resources");
        if (jsonArrayresources != null) {
          // ensure the json data is an array
          if (!jsonObj.get("resources").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `resources` to be an array in the JSON string but got `%s`", jsonObj.get("resources").toString()));
          }

          // validate the optional field `resources` (array)
          for (int i = 0; i < jsonArrayresources.size(); i++) {
            V1beta1ClusterResourceSetBindingSpecBindingsInnerResourcesInner.validateJsonElement(jsonArrayresources.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterResourceSetBindingSpecBindingsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterResourceSetBindingSpecBindingsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterResourceSetBindingSpecBindingsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterResourceSetBindingSpecBindingsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterResourceSetBindingSpecBindingsInner>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterResourceSetBindingSpecBindingsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterResourceSetBindingSpecBindingsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterResourceSetBindingSpecBindingsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterResourceSetBindingSpecBindingsInner
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterResourceSetBindingSpecBindingsInner
  */
  public static V1beta1ClusterResourceSetBindingSpecBindingsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterResourceSetBindingSpecBindingsInner.class);
  }

 /**
  * Convert an instance of V1beta1ClusterResourceSetBindingSpecBindingsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

