/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.x_k8s.cluster.models.V1beta1ClusterClassStatusVariablesInnerDefinitionsInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * ClusterClassStatusVariable defines a variable which appears in the status of a ClusterClass.
 */
@ApiModel(description = "ClusterClassStatusVariable defines a variable which appears in the status of a ClusterClass.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterClassStatusVariablesInner {
  public static final String SERIALIZED_NAME_DEFINITIONS = "definitions";
  @SerializedName(SERIALIZED_NAME_DEFINITIONS)
  private List<V1beta1ClusterClassStatusVariablesInnerDefinitionsInner> definitions = new ArrayList<>();

  public static final String SERIALIZED_NAME_DEFINITIONS_CONFLICT = "definitionsConflict";
  @SerializedName(SERIALIZED_NAME_DEFINITIONS_CONFLICT)
  private Boolean definitionsConflict;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public V1beta1ClusterClassStatusVariablesInner() {
  }

  public V1beta1ClusterClassStatusVariablesInner definitions(List<V1beta1ClusterClassStatusVariablesInnerDefinitionsInner> definitions) {
    this.definitions = definitions;
    return this;
  }

  public V1beta1ClusterClassStatusVariablesInner addDefinitionsItem(V1beta1ClusterClassStatusVariablesInnerDefinitionsInner definitionsItem) {
    if (this.definitions == null) {
      this.definitions = new ArrayList<>();
    }
    this.definitions.add(definitionsItem);
    return this;
  }

   /**
   * Definitions is a list of definitions for a variable.
   * @return definitions
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Definitions is a list of definitions for a variable.")
  public List<V1beta1ClusterClassStatusVariablesInnerDefinitionsInner> getDefinitions() {
    return definitions;
  }

  public void setDefinitions(List<V1beta1ClusterClassStatusVariablesInnerDefinitionsInner> definitions) {
    this.definitions = definitions;
  }


  public V1beta1ClusterClassStatusVariablesInner definitionsConflict(Boolean definitionsConflict) {
    this.definitionsConflict = definitionsConflict;
    return this;
  }

   /**
   * DefinitionsConflict specifies whether or not there are conflicting definitions for a single variable name.
   * @return definitionsConflict
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "DefinitionsConflict specifies whether or not there are conflicting definitions for a single variable name.")
  public Boolean getDefinitionsConflict() {
    return definitionsConflict;
  }

  public void setDefinitionsConflict(Boolean definitionsConflict) {
    this.definitionsConflict = definitionsConflict;
  }


  public V1beta1ClusterClassStatusVariablesInner name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name is the name of the variable.
   * @return name
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Name is the name of the variable.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterClassStatusVariablesInner v1beta1ClusterClassStatusVariablesInner = (V1beta1ClusterClassStatusVariablesInner) o;
    return Objects.equals(this.definitions, v1beta1ClusterClassStatusVariablesInner.definitions) &&
        Objects.equals(this.definitionsConflict, v1beta1ClusterClassStatusVariablesInner.definitionsConflict) &&
        Objects.equals(this.name, v1beta1ClusterClassStatusVariablesInner.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(definitions, definitionsConflict, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterClassStatusVariablesInner {\n");
    sb.append("    definitions: ").append(toIndentedString(definitions)).append("\n");
    sb.append("    definitionsConflict: ").append(toIndentedString(definitionsConflict)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("definitions");
    openapiFields.add("definitionsConflict");
    openapiFields.add("name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("definitions");
    openapiRequiredFields.add("name");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterClassStatusVariablesInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterClassStatusVariablesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterClassStatusVariablesInner is not found in the empty JSON string", V1beta1ClusterClassStatusVariablesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterClassStatusVariablesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterClassStatusVariablesInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1beta1ClusterClassStatusVariablesInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("definitions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `definitions` to be an array in the JSON string but got `%s`", jsonObj.get("definitions").toString()));
      }

      JsonArray jsonArraydefinitions = jsonObj.getAsJsonArray("definitions");
      // validate the required field `definitions` (array)
      for (int i = 0; i < jsonArraydefinitions.size(); i++) {
        V1beta1ClusterClassStatusVariablesInnerDefinitionsInner.validateJsonElement(jsonArraydefinitions.get(i));
      };
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterClassStatusVariablesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterClassStatusVariablesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterClassStatusVariablesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterClassStatusVariablesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterClassStatusVariablesInner>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterClassStatusVariablesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterClassStatusVariablesInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterClassStatusVariablesInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterClassStatusVariablesInner
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterClassStatusVariablesInner
  */
  public static V1beta1ClusterClassStatusVariablesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterClassStatusVariablesInner.class);
  }

 /**
  * Convert an instance of V1beta1ClusterClassStatusVariablesInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

