/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * MachineDeploymentClass selects templates referenced in specific MachineDeploymentClasses in .spec.workers.machineDeployments.
 */
@ApiModel(description = "MachineDeploymentClass selects templates referenced in specific MachineDeploymentClasses in .spec.workers.machineDeployments.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass {
  public static final String SERIALIZED_NAME_NAMES = "names";
  @SerializedName(SERIALIZED_NAME_NAMES)
  private List<String> names = new ArrayList<>();

  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass() {
  }

  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass names(List<String> names) {
    this.names = names;
    return this;
  }

  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass addNamesItem(String namesItem) {
    if (this.names == null) {
      this.names = new ArrayList<>();
    }
    this.names.add(namesItem);
    return this;
  }

   /**
   * Names selects templates by class names.
   * @return names
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Names selects templates by class names.")
  public List<String> getNames() {
    return names;
  }

  public void setNames(List<String> names) {
    this.names = names;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass v1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass = (V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass) o;
    return Objects.equals(this.names, v1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass.names);
  }

  @Override
  public int hashCode() {
    return Objects.hash(names);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass {\n");
    sb.append("    names: ").append(toIndentedString(names)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("names");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass is not found in the empty JSON string", V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("names") != null && !jsonObj.get("names").isJsonNull() && !jsonObj.get("names").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `names` to be an array in the JSON string but got `%s`", jsonObj.get("names").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass
  */
  public static V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass.class);
  }

 /**
  * Convert an instance of V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

