/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.x_k8s.cluster.models.V1beta1ClusterClassSpecVariablesInnerSchema;
import io.x_k8s.cluster.models.V1beta1ClusterClassStatusVariablesInnerDefinitionsInnerMetadata;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * ClusterClassStatusVariableDefinition defines a variable which appears in the status of a ClusterClass.
 */
@ApiModel(description = "ClusterClassStatusVariableDefinition defines a variable which appears in the status of a ClusterClass.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterClassStatusVariablesInnerDefinitionsInner {
  public static final String SERIALIZED_NAME_FROM = "from";
  @SerializedName(SERIALIZED_NAME_FROM)
  private String from;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private V1beta1ClusterClassStatusVariablesInnerDefinitionsInnerMetadata metadata;

  public static final String SERIALIZED_NAME_REQUIRED = "required";
  @SerializedName(SERIALIZED_NAME_REQUIRED)
  private Boolean required;

  public static final String SERIALIZED_NAME_SCHEMA = "schema";
  @SerializedName(SERIALIZED_NAME_SCHEMA)
  private V1beta1ClusterClassSpecVariablesInnerSchema schema;

  public V1beta1ClusterClassStatusVariablesInnerDefinitionsInner() {
  }

  public V1beta1ClusterClassStatusVariablesInnerDefinitionsInner from(String from) {
    this.from = from;
    return this;
  }

   /**
   * From specifies the origin of the variable definition. This will be &#x60;inline&#x60; for variables defined in the ClusterClass or the name of a patch defined in the ClusterClass for variables discovered from a DiscoverVariables runtime extensions.
   * @return from
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "From specifies the origin of the variable definition. This will be `inline` for variables defined in the ClusterClass or the name of a patch defined in the ClusterClass for variables discovered from a DiscoverVariables runtime extensions.")
  public String getFrom() {
    return from;
  }

  public void setFrom(String from) {
    this.from = from;
  }


  public V1beta1ClusterClassStatusVariablesInnerDefinitionsInner metadata(V1beta1ClusterClassStatusVariablesInnerDefinitionsInnerMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1beta1ClusterClassStatusVariablesInnerDefinitionsInnerMetadata getMetadata() {
    return metadata;
  }

  public void setMetadata(V1beta1ClusterClassStatusVariablesInnerDefinitionsInnerMetadata metadata) {
    this.metadata = metadata;
  }


  public V1beta1ClusterClassStatusVariablesInnerDefinitionsInner required(Boolean required) {
    this.required = required;
    return this;
  }

   /**
   * Required specifies if the variable is required. Note: this applies to the variable as a whole and thus the top-level object defined in the schema. If nested fields are required, this will be specified inside the schema.
   * @return required
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Required specifies if the variable is required. Note: this applies to the variable as a whole and thus the top-level object defined in the schema. If nested fields are required, this will be specified inside the schema.")
  public Boolean getRequired() {
    return required;
  }

  public void setRequired(Boolean required) {
    this.required = required;
  }


  public V1beta1ClusterClassStatusVariablesInnerDefinitionsInner schema(V1beta1ClusterClassSpecVariablesInnerSchema schema) {
    this.schema = schema;
    return this;
  }

   /**
   * Get schema
   * @return schema
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  public V1beta1ClusterClassSpecVariablesInnerSchema getSchema() {
    return schema;
  }

  public void setSchema(V1beta1ClusterClassSpecVariablesInnerSchema schema) {
    this.schema = schema;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterClassStatusVariablesInnerDefinitionsInner v1beta1ClusterClassStatusVariablesInnerDefinitionsInner = (V1beta1ClusterClassStatusVariablesInnerDefinitionsInner) o;
    return Objects.equals(this.from, v1beta1ClusterClassStatusVariablesInnerDefinitionsInner.from) &&
        Objects.equals(this.metadata, v1beta1ClusterClassStatusVariablesInnerDefinitionsInner.metadata) &&
        Objects.equals(this.required, v1beta1ClusterClassStatusVariablesInnerDefinitionsInner.required) &&
        Objects.equals(this.schema, v1beta1ClusterClassStatusVariablesInnerDefinitionsInner.schema);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, metadata, required, schema);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterClassStatusVariablesInnerDefinitionsInner {\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("from");
    openapiFields.add("metadata");
    openapiFields.add("required");
    openapiFields.add("schema");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("from");
    openapiRequiredFields.add("required");
    openapiRequiredFields.add("schema");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterClassStatusVariablesInnerDefinitionsInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterClassStatusVariablesInnerDefinitionsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterClassStatusVariablesInnerDefinitionsInner is not found in the empty JSON string", V1beta1ClusterClassStatusVariablesInnerDefinitionsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterClassStatusVariablesInnerDefinitionsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterClassStatusVariablesInnerDefinitionsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1beta1ClusterClassStatusVariablesInnerDefinitionsInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("from").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `from` to be a primitive type in the JSON string but got `%s`", jsonObj.get("from").toString()));
      }
      // validate the optional field `metadata`
      if (jsonObj.get("metadata") != null && !jsonObj.get("metadata").isJsonNull()) {
        V1beta1ClusterClassStatusVariablesInnerDefinitionsInnerMetadata.validateJsonElement(jsonObj.get("metadata"));
      }
      // validate the required field `schema`
      V1beta1ClusterClassSpecVariablesInnerSchema.validateJsonElement(jsonObj.get("schema"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterClassStatusVariablesInnerDefinitionsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterClassStatusVariablesInnerDefinitionsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterClassStatusVariablesInnerDefinitionsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterClassStatusVariablesInnerDefinitionsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterClassStatusVariablesInnerDefinitionsInner>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterClassStatusVariablesInnerDefinitionsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterClassStatusVariablesInnerDefinitionsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterClassStatusVariablesInnerDefinitionsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterClassStatusVariablesInnerDefinitionsInner
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterClassStatusVariablesInnerDefinitionsInner
  */
  public static V1beta1ClusterClassStatusVariablesInnerDefinitionsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterClassStatusVariablesInnerDefinitionsInner.class);
  }

 /**
  * Convert an instance of V1beta1ClusterClassStatusVariablesInnerDefinitionsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

