/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * The network ranges from which Pod networks are allocated.
 */
@ApiModel(description = "The network ranges from which Pod networks are allocated.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterSpecClusterNetworkPods {
  public static final String SERIALIZED_NAME_CIDR_BLOCKS = "cidrBlocks";
  @SerializedName(SERIALIZED_NAME_CIDR_BLOCKS)
  private List<String> cidrBlocks = new ArrayList<>();

  public V1beta1ClusterSpecClusterNetworkPods() {
  }

  public V1beta1ClusterSpecClusterNetworkPods cidrBlocks(List<String> cidrBlocks) {
    this.cidrBlocks = cidrBlocks;
    return this;
  }

  public V1beta1ClusterSpecClusterNetworkPods addCidrBlocksItem(String cidrBlocksItem) {
    if (this.cidrBlocks == null) {
      this.cidrBlocks = new ArrayList<>();
    }
    this.cidrBlocks.add(cidrBlocksItem);
    return this;
  }

   /**
   * Get cidrBlocks
   * @return cidrBlocks
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  public List<String> getCidrBlocks() {
    return cidrBlocks;
  }

  public void setCidrBlocks(List<String> cidrBlocks) {
    this.cidrBlocks = cidrBlocks;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterSpecClusterNetworkPods v1beta1ClusterSpecClusterNetworkPods = (V1beta1ClusterSpecClusterNetworkPods) o;
    return Objects.equals(this.cidrBlocks, v1beta1ClusterSpecClusterNetworkPods.cidrBlocks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cidrBlocks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterSpecClusterNetworkPods {\n");
    sb.append("    cidrBlocks: ").append(toIndentedString(cidrBlocks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cidrBlocks");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("cidrBlocks");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterSpecClusterNetworkPods
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterSpecClusterNetworkPods.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterSpecClusterNetworkPods is not found in the empty JSON string", V1beta1ClusterSpecClusterNetworkPods.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterSpecClusterNetworkPods.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterSpecClusterNetworkPods` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1beta1ClusterSpecClusterNetworkPods.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("cidrBlocks") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("cidrBlocks").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `cidrBlocks` to be an array in the JSON string but got `%s`", jsonObj.get("cidrBlocks").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterSpecClusterNetworkPods.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterSpecClusterNetworkPods' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterSpecClusterNetworkPods> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterSpecClusterNetworkPods.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterSpecClusterNetworkPods>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterSpecClusterNetworkPods value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterSpecClusterNetworkPods read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterSpecClusterNetworkPods given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterSpecClusterNetworkPods
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterSpecClusterNetworkPods
  */
  public static V1beta1ClusterSpecClusterNetworkPods fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterSpecClusterNetworkPods.class);
  }

 /**
  * Convert an instance of V1beta1ClusterSpecClusterNetworkPods to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

