/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.x_k8s.cluster.models.V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * JSONPatch defines a JSON patch.
 */
@ApiModel(description = "JSONPatch defines a JSON patch.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner {
  public static final String SERIALIZED_NAME_OP = "op";
  @SerializedName(SERIALIZED_NAME_OP)
  private String op;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private Object value;

  public static final String SERIALIZED_NAME_VALUE_FROM = "valueFrom";
  @SerializedName(SERIALIZED_NAME_VALUE_FROM)
  private V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom valueFrom;

  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner() {
  }

  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner op(String op) {
    this.op = op;
    return this;
  }

   /**
   * Op defines the operation of the patch. Note: Only &#x60;add&#x60;, &#x60;replace&#x60; and &#x60;remove&#x60; are supported.
   * @return op
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Op defines the operation of the patch. Note: Only `add`, `replace` and `remove` are supported.")
  public String getOp() {
    return op;
  }

  public void setOp(String op) {
    this.op = op;
  }


  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Path defines the path of the patch. Note: Only the spec of a template can be patched, thus the path has to start with /spec/. Note: For now the only allowed array modifications are &#x60;append&#x60; and &#x60;prepend&#x60;, i.e.: * for op: &#x60;add&#x60;: only index 0 (prepend) and - (append) are allowed * for op: &#x60;replace&#x60; or &#x60;remove&#x60;: no indexes are allowed
   * @return path
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Path defines the path of the patch. Note: Only the spec of a template can be patched, thus the path has to start with /spec/. Note: For now the only allowed array modifications are `append` and `prepend`, i.e.: * for op: `add`: only index 0 (prepend) and - (append) are allowed * for op: `replace` or `remove`: no indexes are allowed")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }


  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner value(Object value) {
    this.value = value;
    return this;
  }

   /**
   * Value defines the value of the patch. Note: Either Value or ValueFrom is required for add and replace operations. Only one of them is allowed to be set at the same time. Note: We have to use apiextensionsv1.JSON instead of our JSON type, because controller-tools has a hard-coded schema for apiextensionsv1.JSON which cannot be produced by another type (unset type field). Ref: https://github.com/kubernetes-sigs/controller-tools/blob/d0e03a142d0ecdd5491593e941ee1d6b5d91dba6/pkg/crd/known_types.go#L106-L111
   * @return value
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Value defines the value of the patch. Note: Either Value or ValueFrom is required for add and replace operations. Only one of them is allowed to be set at the same time. Note: We have to use apiextensionsv1.JSON instead of our JSON type, because controller-tools has a hard-coded schema for apiextensionsv1.JSON which cannot be produced by another type (unset type field). Ref: https://github.com/kubernetes-sigs/controller-tools/blob/d0e03a142d0ecdd5491593e941ee1d6b5d91dba6/pkg/crd/known_types.go#L106-L111")
  public Object getValue() {
    return value;
  }

  public void setValue(Object value) {
    this.value = value;
  }


  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner valueFrom(V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom valueFrom) {
    this.valueFrom = valueFrom;
    return this;
  }

   /**
   * Get valueFrom
   * @return valueFrom
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom getValueFrom() {
    return valueFrom;
  }

  public void setValueFrom(V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom valueFrom) {
    this.valueFrom = valueFrom;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner v1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner = (V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner) o;
    return Objects.equals(this.op, v1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner.op) &&
        Objects.equals(this.path, v1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner.path) &&
        Objects.equals(this.value, v1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner.value) &&
        Objects.equals(this.valueFrom, v1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner.valueFrom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(op, path, value, valueFrom);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner {\n");
    sb.append("    op: ").append(toIndentedString(op)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    valueFrom: ").append(toIndentedString(valueFrom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("op");
    openapiFields.add("path");
    openapiFields.add("value");
    openapiFields.add("valueFrom");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("op");
    openapiRequiredFields.add("path");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner is not found in the empty JSON string", V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("op").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `op` to be a primitive type in the JSON string but got `%s`", jsonObj.get("op").toString()));
      }
      if (!jsonObj.get("path").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `path` to be a primitive type in the JSON string but got `%s`", jsonObj.get("path").toString()));
      }
      // validate the optional field `valueFrom`
      if (jsonObj.get("valueFrom") != null && !jsonObj.get("valueFrom").isJsonNull()) {
        V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom.validateJsonElement(jsonObj.get("valueFrom"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner
  */
  public static V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner.class);
  }

 /**
  * Convert an instance of V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

