/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * Remediation controls the strategy of remediating unhealthy machines and how remediating operations should occur during the lifecycle of the dependant MachineSets.
 */
@ApiModel(description = "Remediation controls the strategy of remediating unhealthy machines and how remediating operations should occur during the lifecycle of the dependant MachineSets.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation {
  public static final String SERIALIZED_NAME_MAX_IN_FLIGHT = "maxInFlight";
  @SerializedName(SERIALIZED_NAME_MAX_IN_FLIGHT)
  private Object maxInFlight;

  public V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation() {
  }

  public V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation maxInFlight(Object maxInFlight) {
    this.maxInFlight = maxInFlight;
    return this;
  }

   /**
   * MaxInFlight determines how many in flight remediations should happen at the same time.   Remediation only happens on the MachineSet with the most current revision, while older MachineSets (usually present during rollout operations) aren&#39;t allowed to remediate.   Note: In general (independent of remediations), unhealthy machines are always prioritized during scale down operations over healthy ones.   MaxInFlight can be set to a fixed number or a percentage. Example: when this is set to 20%, the MachineSet controller deletes at most 20% of the desired replicas.   If not set, remediation is limited to all machines (bounded by replicas) under the active MachineSet&#39;s management.
   * @return maxInFlight
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "MaxInFlight determines how many in flight remediations should happen at the same time.   Remediation only happens on the MachineSet with the most current revision, while older MachineSets (usually present during rollout operations) aren't allowed to remediate.   Note: In general (independent of remediations), unhealthy machines are always prioritized during scale down operations over healthy ones.   MaxInFlight can be set to a fixed number or a percentage. Example: when this is set to 20%, the MachineSet controller deletes at most 20% of the desired replicas.   If not set, remediation is limited to all machines (bounded by replicas) under the active MachineSet's management.")
  public Object getMaxInFlight() {
    return maxInFlight;
  }

  public void setMaxInFlight(Object maxInFlight) {
    this.maxInFlight = maxInFlight;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation v1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation = (V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation) o;
    return Objects.equals(this.maxInFlight, v1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation.maxInFlight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxInFlight);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation {\n");
    sb.append("    maxInFlight: ").append(toIndentedString(maxInFlight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("maxInFlight");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation is not found in the empty JSON string", V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation
  */
  public static V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation.class);
  }

 /**
  * Convert an instance of V1beta1ClusterSpecTopologyWorkersMachineDeploymentsInnerStrategyRemediation to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

