/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.x_k8s.cluster.models.V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner;
import io.x_k8s.cluster.models.V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelector;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * PatchDefinition defines a patch which is applied to customize the referenced templates.
 */
@ApiModel(description = "PatchDefinition defines a patch which is applied to customize the referenced templates.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterClassSpecPatchesInnerDefinitionsInner {
  public static final String SERIALIZED_NAME_JSON_PATCHES = "jsonPatches";
  @SerializedName(SERIALIZED_NAME_JSON_PATCHES)
  private List<V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner> jsonPatches = new ArrayList<>();

  public static final String SERIALIZED_NAME_SELECTOR = "selector";
  @SerializedName(SERIALIZED_NAME_SELECTOR)
  private V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelector selector;

  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInner() {
  }

  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInner jsonPatches(List<V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner> jsonPatches) {
    this.jsonPatches = jsonPatches;
    return this;
  }

  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInner addJsonPatchesItem(V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner jsonPatchesItem) {
    if (this.jsonPatches == null) {
      this.jsonPatches = new ArrayList<>();
    }
    this.jsonPatches.add(jsonPatchesItem);
    return this;
  }

   /**
   * JSONPatches defines the patches which should be applied on the templates matching the selector. Note: Patches will be applied in the order of the array.
   * @return jsonPatches
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "JSONPatches defines the patches which should be applied on the templates matching the selector. Note: Patches will be applied in the order of the array.")
  public List<V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner> getJsonPatches() {
    return jsonPatches;
  }

  public void setJsonPatches(List<V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner> jsonPatches) {
    this.jsonPatches = jsonPatches;
  }


  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInner selector(V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelector selector) {
    this.selector = selector;
    return this;
  }

   /**
   * Get selector
   * @return selector
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelector getSelector() {
    return selector;
  }

  public void setSelector(V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelector selector) {
    this.selector = selector;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterClassSpecPatchesInnerDefinitionsInner v1beta1ClusterClassSpecPatchesInnerDefinitionsInner = (V1beta1ClusterClassSpecPatchesInnerDefinitionsInner) o;
    return Objects.equals(this.jsonPatches, v1beta1ClusterClassSpecPatchesInnerDefinitionsInner.jsonPatches) &&
        Objects.equals(this.selector, v1beta1ClusterClassSpecPatchesInnerDefinitionsInner.selector);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jsonPatches, selector);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterClassSpecPatchesInnerDefinitionsInner {\n");
    sb.append("    jsonPatches: ").append(toIndentedString(jsonPatches)).append("\n");
    sb.append("    selector: ").append(toIndentedString(selector)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("jsonPatches");
    openapiFields.add("selector");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("jsonPatches");
    openapiRequiredFields.add("selector");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterClassSpecPatchesInnerDefinitionsInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterClassSpecPatchesInnerDefinitionsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterClassSpecPatchesInnerDefinitionsInner is not found in the empty JSON string", V1beta1ClusterClassSpecPatchesInnerDefinitionsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterClassSpecPatchesInnerDefinitionsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterClassSpecPatchesInnerDefinitionsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1beta1ClusterClassSpecPatchesInnerDefinitionsInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("jsonPatches").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `jsonPatches` to be an array in the JSON string but got `%s`", jsonObj.get("jsonPatches").toString()));
      }

      JsonArray jsonArrayjsonPatches = jsonObj.getAsJsonArray("jsonPatches");
      // validate the required field `jsonPatches` (array)
      for (int i = 0; i < jsonArrayjsonPatches.size(); i++) {
        V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInner.validateJsonElement(jsonArrayjsonPatches.get(i));
      };
      // validate the required field `selector`
      V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelector.validateJsonElement(jsonObj.get("selector"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterClassSpecPatchesInnerDefinitionsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterClassSpecPatchesInnerDefinitionsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterClassSpecPatchesInnerDefinitionsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterClassSpecPatchesInnerDefinitionsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterClassSpecPatchesInnerDefinitionsInner>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterClassSpecPatchesInnerDefinitionsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterClassSpecPatchesInnerDefinitionsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterClassSpecPatchesInnerDefinitionsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterClassSpecPatchesInnerDefinitionsInner
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterClassSpecPatchesInnerDefinitionsInner
  */
  public static V1beta1ClusterClassSpecPatchesInnerDefinitionsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterClassSpecPatchesInnerDefinitionsInner.class);
  }

 /**
  * Convert an instance of V1beta1ClusterClassSpecPatchesInnerDefinitionsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

