/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.x_k8s.cluster.models.V1beta1ClusterSpecClusterNetworkPods;
import io.x_k8s.cluster.models.V1beta1ClusterSpecClusterNetworkServices;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * Cluster network configuration.
 */
@ApiModel(description = "Cluster network configuration.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterSpecClusterNetwork {
  public static final String SERIALIZED_NAME_API_SERVER_PORT = "apiServerPort";
  @SerializedName(SERIALIZED_NAME_API_SERVER_PORT)
  private Integer apiServerPort;

  public static final String SERIALIZED_NAME_PODS = "pods";
  @SerializedName(SERIALIZED_NAME_PODS)
  private V1beta1ClusterSpecClusterNetworkPods pods;

  public static final String SERIALIZED_NAME_SERVICE_DOMAIN = "serviceDomain";
  @SerializedName(SERIALIZED_NAME_SERVICE_DOMAIN)
  private String serviceDomain;

  public static final String SERIALIZED_NAME_SERVICES = "services";
  @SerializedName(SERIALIZED_NAME_SERVICES)
  private V1beta1ClusterSpecClusterNetworkServices services;

  public V1beta1ClusterSpecClusterNetwork() {
  }

  public V1beta1ClusterSpecClusterNetwork apiServerPort(Integer apiServerPort) {
    this.apiServerPort = apiServerPort;
    return this;
  }

   /**
   * APIServerPort specifies the port the API Server should bind to. Defaults to 6443.
   * @return apiServerPort
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "APIServerPort specifies the port the API Server should bind to. Defaults to 6443.")
  public Integer getApiServerPort() {
    return apiServerPort;
  }

  public void setApiServerPort(Integer apiServerPort) {
    this.apiServerPort = apiServerPort;
  }


  public V1beta1ClusterSpecClusterNetwork pods(V1beta1ClusterSpecClusterNetworkPods pods) {
    this.pods = pods;
    return this;
  }

   /**
   * Get pods
   * @return pods
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1beta1ClusterSpecClusterNetworkPods getPods() {
    return pods;
  }

  public void setPods(V1beta1ClusterSpecClusterNetworkPods pods) {
    this.pods = pods;
  }


  public V1beta1ClusterSpecClusterNetwork serviceDomain(String serviceDomain) {
    this.serviceDomain = serviceDomain;
    return this;
  }

   /**
   * Domain name for services.
   * @return serviceDomain
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Domain name for services.")
  public String getServiceDomain() {
    return serviceDomain;
  }

  public void setServiceDomain(String serviceDomain) {
    this.serviceDomain = serviceDomain;
  }


  public V1beta1ClusterSpecClusterNetwork services(V1beta1ClusterSpecClusterNetworkServices services) {
    this.services = services;
    return this;
  }

   /**
   * Get services
   * @return services
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1beta1ClusterSpecClusterNetworkServices getServices() {
    return services;
  }

  public void setServices(V1beta1ClusterSpecClusterNetworkServices services) {
    this.services = services;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterSpecClusterNetwork v1beta1ClusterSpecClusterNetwork = (V1beta1ClusterSpecClusterNetwork) o;
    return Objects.equals(this.apiServerPort, v1beta1ClusterSpecClusterNetwork.apiServerPort) &&
        Objects.equals(this.pods, v1beta1ClusterSpecClusterNetwork.pods) &&
        Objects.equals(this.serviceDomain, v1beta1ClusterSpecClusterNetwork.serviceDomain) &&
        Objects.equals(this.services, v1beta1ClusterSpecClusterNetwork.services);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiServerPort, pods, serviceDomain, services);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterSpecClusterNetwork {\n");
    sb.append("    apiServerPort: ").append(toIndentedString(apiServerPort)).append("\n");
    sb.append("    pods: ").append(toIndentedString(pods)).append("\n");
    sb.append("    serviceDomain: ").append(toIndentedString(serviceDomain)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("apiServerPort");
    openapiFields.add("pods");
    openapiFields.add("serviceDomain");
    openapiFields.add("services");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterSpecClusterNetwork
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterSpecClusterNetwork.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterSpecClusterNetwork is not found in the empty JSON string", V1beta1ClusterSpecClusterNetwork.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterSpecClusterNetwork.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterSpecClusterNetwork` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `pods`
      if (jsonObj.get("pods") != null && !jsonObj.get("pods").isJsonNull()) {
        V1beta1ClusterSpecClusterNetworkPods.validateJsonElement(jsonObj.get("pods"));
      }
      if ((jsonObj.get("serviceDomain") != null && !jsonObj.get("serviceDomain").isJsonNull()) && !jsonObj.get("serviceDomain").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serviceDomain` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serviceDomain").toString()));
      }
      // validate the optional field `services`
      if (jsonObj.get("services") != null && !jsonObj.get("services").isJsonNull()) {
        V1beta1ClusterSpecClusterNetworkServices.validateJsonElement(jsonObj.get("services"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterSpecClusterNetwork.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterSpecClusterNetwork' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterSpecClusterNetwork> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterSpecClusterNetwork.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterSpecClusterNetwork>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterSpecClusterNetwork value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterSpecClusterNetwork read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterSpecClusterNetwork given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterSpecClusterNetwork
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterSpecClusterNetwork
  */
  public static V1beta1ClusterSpecClusterNetwork fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterSpecClusterNetwork.class);
  }

 /**
  * Convert an instance of V1beta1ClusterSpecClusterNetwork to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

