/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.x_k8s.cluster.models.V1beta1ClusterResourceSetBindingSpecBindingsInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * ClusterResourceSetBindingSpec defines the desired state of ClusterResourceSetBinding.
 */
@ApiModel(description = "ClusterResourceSetBindingSpec defines the desired state of ClusterResourceSetBinding.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterResourceSetBindingSpec {
  public static final String SERIALIZED_NAME_BINDINGS = "bindings";
  @SerializedName(SERIALIZED_NAME_BINDINGS)
  private List<V1beta1ClusterResourceSetBindingSpecBindingsInner> bindings = new ArrayList<>();

  public static final String SERIALIZED_NAME_CLUSTER_NAME = "clusterName";
  @SerializedName(SERIALIZED_NAME_CLUSTER_NAME)
  private String clusterName;

  public V1beta1ClusterResourceSetBindingSpec() {
  }

  public V1beta1ClusterResourceSetBindingSpec bindings(List<V1beta1ClusterResourceSetBindingSpecBindingsInner> bindings) {
    this.bindings = bindings;
    return this;
  }

  public V1beta1ClusterResourceSetBindingSpec addBindingsItem(V1beta1ClusterResourceSetBindingSpecBindingsInner bindingsItem) {
    if (this.bindings == null) {
      this.bindings = new ArrayList<>();
    }
    this.bindings.add(bindingsItem);
    return this;
  }

   /**
   * Bindings is a list of ClusterResourceSets and their resources.
   * @return bindings
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Bindings is a list of ClusterResourceSets and their resources.")
  public List<V1beta1ClusterResourceSetBindingSpecBindingsInner> getBindings() {
    return bindings;
  }

  public void setBindings(List<V1beta1ClusterResourceSetBindingSpecBindingsInner> bindings) {
    this.bindings = bindings;
  }


  public V1beta1ClusterResourceSetBindingSpec clusterName(String clusterName) {
    this.clusterName = clusterName;
    return this;
  }

   /**
   * ClusterName is the name of the Cluster this binding applies to. Note: this field mandatory in v1beta2.
   * @return clusterName
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "ClusterName is the name of the Cluster this binding applies to. Note: this field mandatory in v1beta2.")
  public String getClusterName() {
    return clusterName;
  }

  public void setClusterName(String clusterName) {
    this.clusterName = clusterName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterResourceSetBindingSpec v1beta1ClusterResourceSetBindingSpec = (V1beta1ClusterResourceSetBindingSpec) o;
    return Objects.equals(this.bindings, v1beta1ClusterResourceSetBindingSpec.bindings) &&
        Objects.equals(this.clusterName, v1beta1ClusterResourceSetBindingSpec.clusterName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bindings, clusterName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterResourceSetBindingSpec {\n");
    sb.append("    bindings: ").append(toIndentedString(bindings)).append("\n");
    sb.append("    clusterName: ").append(toIndentedString(clusterName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("bindings");
    openapiFields.add("clusterName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterResourceSetBindingSpec
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterResourceSetBindingSpec.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterResourceSetBindingSpec is not found in the empty JSON string", V1beta1ClusterResourceSetBindingSpec.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterResourceSetBindingSpec.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterResourceSetBindingSpec` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("bindings") != null && !jsonObj.get("bindings").isJsonNull()) {
        JsonArray jsonArraybindings = jsonObj.getAsJsonArray("bindings");
        if (jsonArraybindings != null) {
          // ensure the json data is an array
          if (!jsonObj.get("bindings").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `bindings` to be an array in the JSON string but got `%s`", jsonObj.get("bindings").toString()));
          }

          // validate the optional field `bindings` (array)
          for (int i = 0; i < jsonArraybindings.size(); i++) {
            V1beta1ClusterResourceSetBindingSpecBindingsInner.validateJsonElement(jsonArraybindings.get(i));
          };
        }
      }
      if ((jsonObj.get("clusterName") != null && !jsonObj.get("clusterName").isJsonNull()) && !jsonObj.get("clusterName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clusterName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clusterName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterResourceSetBindingSpec.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterResourceSetBindingSpec' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterResourceSetBindingSpec> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterResourceSetBindingSpec.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterResourceSetBindingSpec>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterResourceSetBindingSpec value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterResourceSetBindingSpec read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterResourceSetBindingSpec given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterResourceSetBindingSpec
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterResourceSetBindingSpec
  */
  public static V1beta1ClusterResourceSetBindingSpec fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterResourceSetBindingSpec.class);
  }

 /**
  * Convert an instance of V1beta1ClusterResourceSetBindingSpec to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

