/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.x_k8s.cluster.models.V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass;
import io.x_k8s.cluster.models.V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachinePoolClass;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * MatchResources selects templates based on where they are referenced.
 */
@ApiModel(description = "MatchResources selects templates based on where they are referenced.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources {
  public static final String SERIALIZED_NAME_CONTROL_PLANE = "controlPlane";
  @SerializedName(SERIALIZED_NAME_CONTROL_PLANE)
  private Boolean controlPlane;

  public static final String SERIALIZED_NAME_INFRASTRUCTURE_CLUSTER = "infrastructureCluster";
  @SerializedName(SERIALIZED_NAME_INFRASTRUCTURE_CLUSTER)
  private Boolean infrastructureCluster;

  public static final String SERIALIZED_NAME_MACHINE_DEPLOYMENT_CLASS = "machineDeploymentClass";
  @SerializedName(SERIALIZED_NAME_MACHINE_DEPLOYMENT_CLASS)
  private V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass machineDeploymentClass;

  public static final String SERIALIZED_NAME_MACHINE_POOL_CLASS = "machinePoolClass";
  @SerializedName(SERIALIZED_NAME_MACHINE_POOL_CLASS)
  private V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachinePoolClass machinePoolClass;

  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources() {
  }

  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources controlPlane(Boolean controlPlane) {
    this.controlPlane = controlPlane;
    return this;
  }

   /**
   * ControlPlane selects templates referenced in .spec.ControlPlane. Note: this will match the controlPlane and also the controlPlane machineInfrastructure (depending on the kind and apiVersion).
   * @return controlPlane
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "ControlPlane selects templates referenced in .spec.ControlPlane. Note: this will match the controlPlane and also the controlPlane machineInfrastructure (depending on the kind and apiVersion).")
  public Boolean getControlPlane() {
    return controlPlane;
  }

  public void setControlPlane(Boolean controlPlane) {
    this.controlPlane = controlPlane;
  }


  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources infrastructureCluster(Boolean infrastructureCluster) {
    this.infrastructureCluster = infrastructureCluster;
    return this;
  }

   /**
   * InfrastructureCluster selects templates referenced in .spec.infrastructure.
   * @return infrastructureCluster
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "InfrastructureCluster selects templates referenced in .spec.infrastructure.")
  public Boolean getInfrastructureCluster() {
    return infrastructureCluster;
  }

  public void setInfrastructureCluster(Boolean infrastructureCluster) {
    this.infrastructureCluster = infrastructureCluster;
  }


  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources machineDeploymentClass(V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass machineDeploymentClass) {
    this.machineDeploymentClass = machineDeploymentClass;
    return this;
  }

   /**
   * Get machineDeploymentClass
   * @return machineDeploymentClass
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass getMachineDeploymentClass() {
    return machineDeploymentClass;
  }

  public void setMachineDeploymentClass(V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass machineDeploymentClass) {
    this.machineDeploymentClass = machineDeploymentClass;
  }


  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources machinePoolClass(V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachinePoolClass machinePoolClass) {
    this.machinePoolClass = machinePoolClass;
    return this;
  }

   /**
   * Get machinePoolClass
   * @return machinePoolClass
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachinePoolClass getMachinePoolClass() {
    return machinePoolClass;
  }

  public void setMachinePoolClass(V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachinePoolClass machinePoolClass) {
    this.machinePoolClass = machinePoolClass;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources v1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources = (V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources) o;
    return Objects.equals(this.controlPlane, v1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources.controlPlane) &&
        Objects.equals(this.infrastructureCluster, v1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources.infrastructureCluster) &&
        Objects.equals(this.machineDeploymentClass, v1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources.machineDeploymentClass) &&
        Objects.equals(this.machinePoolClass, v1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources.machinePoolClass);
  }

  @Override
  public int hashCode() {
    return Objects.hash(controlPlane, infrastructureCluster, machineDeploymentClass, machinePoolClass);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources {\n");
    sb.append("    controlPlane: ").append(toIndentedString(controlPlane)).append("\n");
    sb.append("    infrastructureCluster: ").append(toIndentedString(infrastructureCluster)).append("\n");
    sb.append("    machineDeploymentClass: ").append(toIndentedString(machineDeploymentClass)).append("\n");
    sb.append("    machinePoolClass: ").append(toIndentedString(machinePoolClass)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("controlPlane");
    openapiFields.add("infrastructureCluster");
    openapiFields.add("machineDeploymentClass");
    openapiFields.add("machinePoolClass");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources is not found in the empty JSON string", V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `machineDeploymentClass`
      if (jsonObj.get("machineDeploymentClass") != null && !jsonObj.get("machineDeploymentClass").isJsonNull()) {
        V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachineDeploymentClass.validateJsonElement(jsonObj.get("machineDeploymentClass"));
      }
      // validate the optional field `machinePoolClass`
      if (jsonObj.get("machinePoolClass") != null && !jsonObj.get("machinePoolClass").isJsonNull()) {
        V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResourcesMachinePoolClass.validateJsonElement(jsonObj.get("machinePoolClass"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources
  */
  public static V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources.class);
  }

 /**
  * Convert an instance of V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerSelectorMatchResources to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

