/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.x_k8s.cluster.models.V1beta1ClusterClassSpecWorkersMachineDeploymentsInner;
import io.x_k8s.cluster.models.V1beta1ClusterClassSpecWorkersMachinePoolsInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * Workers describes the worker nodes for the cluster. It is a collection of node types which can be used to create the worker nodes of the cluster.
 */
@ApiModel(description = "Workers describes the worker nodes for the cluster. It is a collection of node types which can be used to create the worker nodes of the cluster.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterClassSpecWorkers {
  public static final String SERIALIZED_NAME_MACHINE_DEPLOYMENTS = "machineDeployments";
  @SerializedName(SERIALIZED_NAME_MACHINE_DEPLOYMENTS)
  private List<V1beta1ClusterClassSpecWorkersMachineDeploymentsInner> machineDeployments = new ArrayList<>();

  public static final String SERIALIZED_NAME_MACHINE_POOLS = "machinePools";
  @SerializedName(SERIALIZED_NAME_MACHINE_POOLS)
  private List<V1beta1ClusterClassSpecWorkersMachinePoolsInner> machinePools = new ArrayList<>();

  public V1beta1ClusterClassSpecWorkers() {
  }

  public V1beta1ClusterClassSpecWorkers machineDeployments(List<V1beta1ClusterClassSpecWorkersMachineDeploymentsInner> machineDeployments) {
    this.machineDeployments = machineDeployments;
    return this;
  }

  public V1beta1ClusterClassSpecWorkers addMachineDeploymentsItem(V1beta1ClusterClassSpecWorkersMachineDeploymentsInner machineDeploymentsItem) {
    if (this.machineDeployments == null) {
      this.machineDeployments = new ArrayList<>();
    }
    this.machineDeployments.add(machineDeploymentsItem);
    return this;
  }

   /**
   * MachineDeployments is a list of machine deployment classes that can be used to create a set of worker nodes.
   * @return machineDeployments
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "MachineDeployments is a list of machine deployment classes that can be used to create a set of worker nodes.")
  public List<V1beta1ClusterClassSpecWorkersMachineDeploymentsInner> getMachineDeployments() {
    return machineDeployments;
  }

  public void setMachineDeployments(List<V1beta1ClusterClassSpecWorkersMachineDeploymentsInner> machineDeployments) {
    this.machineDeployments = machineDeployments;
  }


  public V1beta1ClusterClassSpecWorkers machinePools(List<V1beta1ClusterClassSpecWorkersMachinePoolsInner> machinePools) {
    this.machinePools = machinePools;
    return this;
  }

  public V1beta1ClusterClassSpecWorkers addMachinePoolsItem(V1beta1ClusterClassSpecWorkersMachinePoolsInner machinePoolsItem) {
    if (this.machinePools == null) {
      this.machinePools = new ArrayList<>();
    }
    this.machinePools.add(machinePoolsItem);
    return this;
  }

   /**
   * MachinePools is a list of machine pool classes that can be used to create a set of worker nodes.
   * @return machinePools
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "MachinePools is a list of machine pool classes that can be used to create a set of worker nodes.")
  public List<V1beta1ClusterClassSpecWorkersMachinePoolsInner> getMachinePools() {
    return machinePools;
  }

  public void setMachinePools(List<V1beta1ClusterClassSpecWorkersMachinePoolsInner> machinePools) {
    this.machinePools = machinePools;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterClassSpecWorkers v1beta1ClusterClassSpecWorkers = (V1beta1ClusterClassSpecWorkers) o;
    return Objects.equals(this.machineDeployments, v1beta1ClusterClassSpecWorkers.machineDeployments) &&
        Objects.equals(this.machinePools, v1beta1ClusterClassSpecWorkers.machinePools);
  }

  @Override
  public int hashCode() {
    return Objects.hash(machineDeployments, machinePools);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterClassSpecWorkers {\n");
    sb.append("    machineDeployments: ").append(toIndentedString(machineDeployments)).append("\n");
    sb.append("    machinePools: ").append(toIndentedString(machinePools)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("machineDeployments");
    openapiFields.add("machinePools");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterClassSpecWorkers
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterClassSpecWorkers.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterClassSpecWorkers is not found in the empty JSON string", V1beta1ClusterClassSpecWorkers.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterClassSpecWorkers.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterClassSpecWorkers` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("machineDeployments") != null && !jsonObj.get("machineDeployments").isJsonNull()) {
        JsonArray jsonArraymachineDeployments = jsonObj.getAsJsonArray("machineDeployments");
        if (jsonArraymachineDeployments != null) {
          // ensure the json data is an array
          if (!jsonObj.get("machineDeployments").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `machineDeployments` to be an array in the JSON string but got `%s`", jsonObj.get("machineDeployments").toString()));
          }

          // validate the optional field `machineDeployments` (array)
          for (int i = 0; i < jsonArraymachineDeployments.size(); i++) {
            V1beta1ClusterClassSpecWorkersMachineDeploymentsInner.validateJsonElement(jsonArraymachineDeployments.get(i));
          };
        }
      }
      if (jsonObj.get("machinePools") != null && !jsonObj.get("machinePools").isJsonNull()) {
        JsonArray jsonArraymachinePools = jsonObj.getAsJsonArray("machinePools");
        if (jsonArraymachinePools != null) {
          // ensure the json data is an array
          if (!jsonObj.get("machinePools").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `machinePools` to be an array in the JSON string but got `%s`", jsonObj.get("machinePools").toString()));
          }

          // validate the optional field `machinePools` (array)
          for (int i = 0; i < jsonArraymachinePools.size(); i++) {
            V1beta1ClusterClassSpecWorkersMachinePoolsInner.validateJsonElement(jsonArraymachinePools.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterClassSpecWorkers.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterClassSpecWorkers' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterClassSpecWorkers> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterClassSpecWorkers.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterClassSpecWorkers>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterClassSpecWorkers value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterClassSpecWorkers read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterClassSpecWorkers given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterClassSpecWorkers
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterClassSpecWorkers
  */
  public static V1beta1ClusterClassSpecWorkers fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterClassSpecWorkers.class);
  }

 /**
  * Convert an instance of V1beta1ClusterClassSpecWorkers to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

