/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.x_k8s.cluster.models.V1beta1ClusterClassSpecControlPlane;
import io.x_k8s.cluster.models.V1beta1ClusterClassSpecInfrastructure;
import io.x_k8s.cluster.models.V1beta1ClusterClassSpecPatchesInner;
import io.x_k8s.cluster.models.V1beta1ClusterClassSpecVariablesInner;
import io.x_k8s.cluster.models.V1beta1ClusterClassSpecWorkers;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * ClusterClassSpec describes the desired state of the ClusterClass.
 */
@ApiModel(description = "ClusterClassSpec describes the desired state of the ClusterClass.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterClassSpec {
  public static final String SERIALIZED_NAME_CONTROL_PLANE = "controlPlane";
  @SerializedName(SERIALIZED_NAME_CONTROL_PLANE)
  private V1beta1ClusterClassSpecControlPlane controlPlane;

  public static final String SERIALIZED_NAME_INFRASTRUCTURE = "infrastructure";
  @SerializedName(SERIALIZED_NAME_INFRASTRUCTURE)
  private V1beta1ClusterClassSpecInfrastructure infrastructure;

  public static final String SERIALIZED_NAME_PATCHES = "patches";
  @SerializedName(SERIALIZED_NAME_PATCHES)
  private List<V1beta1ClusterClassSpecPatchesInner> patches = new ArrayList<>();

  public static final String SERIALIZED_NAME_VARIABLES = "variables";
  @SerializedName(SERIALIZED_NAME_VARIABLES)
  private List<V1beta1ClusterClassSpecVariablesInner> variables = new ArrayList<>();

  public static final String SERIALIZED_NAME_WORKERS = "workers";
  @SerializedName(SERIALIZED_NAME_WORKERS)
  private V1beta1ClusterClassSpecWorkers workers;

  public V1beta1ClusterClassSpec() {
  }

  public V1beta1ClusterClassSpec controlPlane(V1beta1ClusterClassSpecControlPlane controlPlane) {
    this.controlPlane = controlPlane;
    return this;
  }

   /**
   * Get controlPlane
   * @return controlPlane
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1beta1ClusterClassSpecControlPlane getControlPlane() {
    return controlPlane;
  }

  public void setControlPlane(V1beta1ClusterClassSpecControlPlane controlPlane) {
    this.controlPlane = controlPlane;
  }


  public V1beta1ClusterClassSpec infrastructure(V1beta1ClusterClassSpecInfrastructure infrastructure) {
    this.infrastructure = infrastructure;
    return this;
  }

   /**
   * Get infrastructure
   * @return infrastructure
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1beta1ClusterClassSpecInfrastructure getInfrastructure() {
    return infrastructure;
  }

  public void setInfrastructure(V1beta1ClusterClassSpecInfrastructure infrastructure) {
    this.infrastructure = infrastructure;
  }


  public V1beta1ClusterClassSpec patches(List<V1beta1ClusterClassSpecPatchesInner> patches) {
    this.patches = patches;
    return this;
  }

  public V1beta1ClusterClassSpec addPatchesItem(V1beta1ClusterClassSpecPatchesInner patchesItem) {
    if (this.patches == null) {
      this.patches = new ArrayList<>();
    }
    this.patches.add(patchesItem);
    return this;
  }

   /**
   * Patches defines the patches which are applied to customize referenced templates of a ClusterClass. Note: Patches will be applied in the order of the array.
   * @return patches
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Patches defines the patches which are applied to customize referenced templates of a ClusterClass. Note: Patches will be applied in the order of the array.")
  public List<V1beta1ClusterClassSpecPatchesInner> getPatches() {
    return patches;
  }

  public void setPatches(List<V1beta1ClusterClassSpecPatchesInner> patches) {
    this.patches = patches;
  }


  public V1beta1ClusterClassSpec variables(List<V1beta1ClusterClassSpecVariablesInner> variables) {
    this.variables = variables;
    return this;
  }

  public V1beta1ClusterClassSpec addVariablesItem(V1beta1ClusterClassSpecVariablesInner variablesItem) {
    if (this.variables == null) {
      this.variables = new ArrayList<>();
    }
    this.variables.add(variablesItem);
    return this;
  }

   /**
   * Variables defines the variables which can be configured in the Cluster topology and are then used in patches.
   * @return variables
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Variables defines the variables which can be configured in the Cluster topology and are then used in patches.")
  public List<V1beta1ClusterClassSpecVariablesInner> getVariables() {
    return variables;
  }

  public void setVariables(List<V1beta1ClusterClassSpecVariablesInner> variables) {
    this.variables = variables;
  }


  public V1beta1ClusterClassSpec workers(V1beta1ClusterClassSpecWorkers workers) {
    this.workers = workers;
    return this;
  }

   /**
   * Get workers
   * @return workers
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1beta1ClusterClassSpecWorkers getWorkers() {
    return workers;
  }

  public void setWorkers(V1beta1ClusterClassSpecWorkers workers) {
    this.workers = workers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterClassSpec v1beta1ClusterClassSpec = (V1beta1ClusterClassSpec) o;
    return Objects.equals(this.controlPlane, v1beta1ClusterClassSpec.controlPlane) &&
        Objects.equals(this.infrastructure, v1beta1ClusterClassSpec.infrastructure) &&
        Objects.equals(this.patches, v1beta1ClusterClassSpec.patches) &&
        Objects.equals(this.variables, v1beta1ClusterClassSpec.variables) &&
        Objects.equals(this.workers, v1beta1ClusterClassSpec.workers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(controlPlane, infrastructure, patches, variables, workers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterClassSpec {\n");
    sb.append("    controlPlane: ").append(toIndentedString(controlPlane)).append("\n");
    sb.append("    infrastructure: ").append(toIndentedString(infrastructure)).append("\n");
    sb.append("    patches: ").append(toIndentedString(patches)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("    workers: ").append(toIndentedString(workers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("controlPlane");
    openapiFields.add("infrastructure");
    openapiFields.add("patches");
    openapiFields.add("variables");
    openapiFields.add("workers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterClassSpec
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterClassSpec.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterClassSpec is not found in the empty JSON string", V1beta1ClusterClassSpec.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterClassSpec.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterClassSpec` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `controlPlane`
      if (jsonObj.get("controlPlane") != null && !jsonObj.get("controlPlane").isJsonNull()) {
        V1beta1ClusterClassSpecControlPlane.validateJsonElement(jsonObj.get("controlPlane"));
      }
      // validate the optional field `infrastructure`
      if (jsonObj.get("infrastructure") != null && !jsonObj.get("infrastructure").isJsonNull()) {
        V1beta1ClusterClassSpecInfrastructure.validateJsonElement(jsonObj.get("infrastructure"));
      }
      if (jsonObj.get("patches") != null && !jsonObj.get("patches").isJsonNull()) {
        JsonArray jsonArraypatches = jsonObj.getAsJsonArray("patches");
        if (jsonArraypatches != null) {
          // ensure the json data is an array
          if (!jsonObj.get("patches").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `patches` to be an array in the JSON string but got `%s`", jsonObj.get("patches").toString()));
          }

          // validate the optional field `patches` (array)
          for (int i = 0; i < jsonArraypatches.size(); i++) {
            V1beta1ClusterClassSpecPatchesInner.validateJsonElement(jsonArraypatches.get(i));
          };
        }
      }
      if (jsonObj.get("variables") != null && !jsonObj.get("variables").isJsonNull()) {
        JsonArray jsonArrayvariables = jsonObj.getAsJsonArray("variables");
        if (jsonArrayvariables != null) {
          // ensure the json data is an array
          if (!jsonObj.get("variables").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `variables` to be an array in the JSON string but got `%s`", jsonObj.get("variables").toString()));
          }

          // validate the optional field `variables` (array)
          for (int i = 0; i < jsonArrayvariables.size(); i++) {
            V1beta1ClusterClassSpecVariablesInner.validateJsonElement(jsonArrayvariables.get(i));
          };
        }
      }
      // validate the optional field `workers`
      if (jsonObj.get("workers") != null && !jsonObj.get("workers").isJsonNull()) {
        V1beta1ClusterClassSpecWorkers.validateJsonElement(jsonObj.get("workers"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterClassSpec.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterClassSpec' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterClassSpec> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterClassSpec.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterClassSpec>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterClassSpec value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterClassSpec read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterClassSpec given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterClassSpec
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterClassSpec
  */
  public static V1beta1ClusterClassSpec fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterClassSpec.class);
  }

 /**
  * Convert an instance of V1beta1ClusterClassSpec to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

