/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.x_k8s.cluster.models.V1beta1ClusterResourceSetSpecClusterSelector;
import io.x_k8s.cluster.models.V1beta1ClusterResourceSetSpecResourcesInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * ClusterResourceSetSpec defines the desired state of ClusterResourceSet.
 */
@ApiModel(description = "ClusterResourceSetSpec defines the desired state of ClusterResourceSet.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterResourceSetSpec {
  public static final String SERIALIZED_NAME_CLUSTER_SELECTOR = "clusterSelector";
  @SerializedName(SERIALIZED_NAME_CLUSTER_SELECTOR)
  private V1beta1ClusterResourceSetSpecClusterSelector clusterSelector;

  public static final String SERIALIZED_NAME_RESOURCES = "resources";
  @SerializedName(SERIALIZED_NAME_RESOURCES)
  private List<V1beta1ClusterResourceSetSpecResourcesInner> resources = new ArrayList<>();

  /**
   * Strategy is the strategy to be used during applying resources. Defaults to ApplyOnce. This field is immutable.
   */
  @JsonAdapter(StrategyEnum.Adapter.class)
  public enum StrategyEnum {
    APPLYONCE("ApplyOnce"),
    
    RECONCILE("Reconcile");

    private String value;

    StrategyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StrategyEnum fromValue(String value) {
      for (StrategyEnum b : StrategyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StrategyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StrategyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StrategyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StrategyEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StrategyEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STRATEGY = "strategy";
  @SerializedName(SERIALIZED_NAME_STRATEGY)
  private StrategyEnum strategy;

  public V1beta1ClusterResourceSetSpec() {
  }

  public V1beta1ClusterResourceSetSpec clusterSelector(V1beta1ClusterResourceSetSpecClusterSelector clusterSelector) {
    this.clusterSelector = clusterSelector;
    return this;
  }

   /**
   * Get clusterSelector
   * @return clusterSelector
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  public V1beta1ClusterResourceSetSpecClusterSelector getClusterSelector() {
    return clusterSelector;
  }

  public void setClusterSelector(V1beta1ClusterResourceSetSpecClusterSelector clusterSelector) {
    this.clusterSelector = clusterSelector;
  }


  public V1beta1ClusterResourceSetSpec resources(List<V1beta1ClusterResourceSetSpecResourcesInner> resources) {
    this.resources = resources;
    return this;
  }

  public V1beta1ClusterResourceSetSpec addResourcesItem(V1beta1ClusterResourceSetSpecResourcesInner resourcesItem) {
    if (this.resources == null) {
      this.resources = new ArrayList<>();
    }
    this.resources.add(resourcesItem);
    return this;
  }

   /**
   * Resources is a list of Secrets/ConfigMaps where each contains 1 or more resources to be applied to remote clusters.
   * @return resources
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Resources is a list of Secrets/ConfigMaps where each contains 1 or more resources to be applied to remote clusters.")
  public List<V1beta1ClusterResourceSetSpecResourcesInner> getResources() {
    return resources;
  }

  public void setResources(List<V1beta1ClusterResourceSetSpecResourcesInner> resources) {
    this.resources = resources;
  }


  public V1beta1ClusterResourceSetSpec strategy(StrategyEnum strategy) {
    this.strategy = strategy;
    return this;
  }

   /**
   * Strategy is the strategy to be used during applying resources. Defaults to ApplyOnce. This field is immutable.
   * @return strategy
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Strategy is the strategy to be used during applying resources. Defaults to ApplyOnce. This field is immutable.")
  public StrategyEnum getStrategy() {
    return strategy;
  }

  public void setStrategy(StrategyEnum strategy) {
    this.strategy = strategy;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterResourceSetSpec v1beta1ClusterResourceSetSpec = (V1beta1ClusterResourceSetSpec) o;
    return Objects.equals(this.clusterSelector, v1beta1ClusterResourceSetSpec.clusterSelector) &&
        Objects.equals(this.resources, v1beta1ClusterResourceSetSpec.resources) &&
        Objects.equals(this.strategy, v1beta1ClusterResourceSetSpec.strategy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clusterSelector, resources, strategy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterResourceSetSpec {\n");
    sb.append("    clusterSelector: ").append(toIndentedString(clusterSelector)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    strategy: ").append(toIndentedString(strategy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("clusterSelector");
    openapiFields.add("resources");
    openapiFields.add("strategy");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("clusterSelector");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterResourceSetSpec
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterResourceSetSpec.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterResourceSetSpec is not found in the empty JSON string", V1beta1ClusterResourceSetSpec.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterResourceSetSpec.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterResourceSetSpec` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1beta1ClusterResourceSetSpec.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `clusterSelector`
      V1beta1ClusterResourceSetSpecClusterSelector.validateJsonElement(jsonObj.get("clusterSelector"));
      if (jsonObj.get("resources") != null && !jsonObj.get("resources").isJsonNull()) {
        JsonArray jsonArrayresources = jsonObj.getAsJsonArray("resources");
        if (jsonArrayresources != null) {
          // ensure the json data is an array
          if (!jsonObj.get("resources").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `resources` to be an array in the JSON string but got `%s`", jsonObj.get("resources").toString()));
          }

          // validate the optional field `resources` (array)
          for (int i = 0; i < jsonArrayresources.size(); i++) {
            V1beta1ClusterResourceSetSpecResourcesInner.validateJsonElement(jsonArrayresources.get(i));
          };
        }
      }
      if ((jsonObj.get("strategy") != null && !jsonObj.get("strategy").isJsonNull()) && !jsonObj.get("strategy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `strategy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("strategy").toString()));
      }
      // validate the optional field `strategy`
      if (jsonObj.get("strategy") != null && !jsonObj.get("strategy").isJsonNull()) {
        StrategyEnum.validateJsonElement(jsonObj.get("strategy"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterResourceSetSpec.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterResourceSetSpec' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterResourceSetSpec> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterResourceSetSpec.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterResourceSetSpec>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterResourceSetSpec value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterResourceSetSpec read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterResourceSetSpec given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterResourceSetSpec
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterResourceSetSpec
  */
  public static V1beta1ClusterResourceSetSpec fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterResourceSetSpec.class);
  }

 /**
  * Convert an instance of V1beta1ClusterResourceSetSpec to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

