/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.x_k8s.cluster.models.V1beta1ClusterSpecTopologyControlPlane;
import io.x_k8s.cluster.models.V1beta1ClusterSpecTopologyControlPlaneVariablesOverridesInner;
import io.x_k8s.cluster.models.V1beta1ClusterSpecTopologyWorkers;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * This encapsulates the topology for the cluster. NOTE: It is required to enable the ClusterTopology feature gate flag to activate managed topologies support; this feature is highly experimental, and parts of it might still be not implemented.
 */
@ApiModel(description = "This encapsulates the topology for the cluster. NOTE: It is required to enable the ClusterTopology feature gate flag to activate managed topologies support; this feature is highly experimental, and parts of it might still be not implemented.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterSpecTopology {
  public static final String SERIALIZED_NAME_PROPERTY_CLASS = "class";
  @SerializedName(SERIALIZED_NAME_PROPERTY_CLASS)
  private String propertyClass;

  public static final String SERIALIZED_NAME_CONTROL_PLANE = "controlPlane";
  @SerializedName(SERIALIZED_NAME_CONTROL_PLANE)
  private V1beta1ClusterSpecTopologyControlPlane controlPlane;

  public static final String SERIALIZED_NAME_ROLLOUT_AFTER = "rolloutAfter";
  @SerializedName(SERIALIZED_NAME_ROLLOUT_AFTER)
  private OffsetDateTime rolloutAfter;

  public static final String SERIALIZED_NAME_VARIABLES = "variables";
  @SerializedName(SERIALIZED_NAME_VARIABLES)
  private List<V1beta1ClusterSpecTopologyControlPlaneVariablesOverridesInner> variables = new ArrayList<>();

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;

  public static final String SERIALIZED_NAME_WORKERS = "workers";
  @SerializedName(SERIALIZED_NAME_WORKERS)
  private V1beta1ClusterSpecTopologyWorkers workers;

  public V1beta1ClusterSpecTopology() {
  }

  public V1beta1ClusterSpecTopology propertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
    return this;
  }

   /**
   * The name of the ClusterClass object to create the topology.
   * @return propertyClass
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The name of the ClusterClass object to create the topology.")
  public String getPropertyClass() {
    return propertyClass;
  }

  public void setPropertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
  }


  public V1beta1ClusterSpecTopology controlPlane(V1beta1ClusterSpecTopologyControlPlane controlPlane) {
    this.controlPlane = controlPlane;
    return this;
  }

   /**
   * Get controlPlane
   * @return controlPlane
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1beta1ClusterSpecTopologyControlPlane getControlPlane() {
    return controlPlane;
  }

  public void setControlPlane(V1beta1ClusterSpecTopologyControlPlane controlPlane) {
    this.controlPlane = controlPlane;
  }


  public V1beta1ClusterSpecTopology rolloutAfter(OffsetDateTime rolloutAfter) {
    this.rolloutAfter = rolloutAfter;
    return this;
  }

   /**
   * RolloutAfter performs a rollout of the entire cluster one component at a time, control plane first and then machine deployments.   Deprecated: This field has no function and is going to be removed in the next apiVersion.
   * @return rolloutAfter
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "RolloutAfter performs a rollout of the entire cluster one component at a time, control plane first and then machine deployments.   Deprecated: This field has no function and is going to be removed in the next apiVersion.")
  public OffsetDateTime getRolloutAfter() {
    return rolloutAfter;
  }

  public void setRolloutAfter(OffsetDateTime rolloutAfter) {
    this.rolloutAfter = rolloutAfter;
  }


  public V1beta1ClusterSpecTopology variables(List<V1beta1ClusterSpecTopologyControlPlaneVariablesOverridesInner> variables) {
    this.variables = variables;
    return this;
  }

  public V1beta1ClusterSpecTopology addVariablesItem(V1beta1ClusterSpecTopologyControlPlaneVariablesOverridesInner variablesItem) {
    if (this.variables == null) {
      this.variables = new ArrayList<>();
    }
    this.variables.add(variablesItem);
    return this;
  }

   /**
   * Variables can be used to customize the Cluster through patches. They must comply to the corresponding VariableClasses defined in the ClusterClass.
   * @return variables
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Variables can be used to customize the Cluster through patches. They must comply to the corresponding VariableClasses defined in the ClusterClass.")
  public List<V1beta1ClusterSpecTopologyControlPlaneVariablesOverridesInner> getVariables() {
    return variables;
  }

  public void setVariables(List<V1beta1ClusterSpecTopologyControlPlaneVariablesOverridesInner> variables) {
    this.variables = variables;
  }


  public V1beta1ClusterSpecTopology version(String version) {
    this.version = version;
    return this;
  }

   /**
   * The Kubernetes version of the cluster.
   * @return version
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The Kubernetes version of the cluster.")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }


  public V1beta1ClusterSpecTopology workers(V1beta1ClusterSpecTopologyWorkers workers) {
    this.workers = workers;
    return this;
  }

   /**
   * Get workers
   * @return workers
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1beta1ClusterSpecTopologyWorkers getWorkers() {
    return workers;
  }

  public void setWorkers(V1beta1ClusterSpecTopologyWorkers workers) {
    this.workers = workers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterSpecTopology v1beta1ClusterSpecTopology = (V1beta1ClusterSpecTopology) o;
    return Objects.equals(this.propertyClass, v1beta1ClusterSpecTopology.propertyClass) &&
        Objects.equals(this.controlPlane, v1beta1ClusterSpecTopology.controlPlane) &&
        Objects.equals(this.rolloutAfter, v1beta1ClusterSpecTopology.rolloutAfter) &&
        Objects.equals(this.variables, v1beta1ClusterSpecTopology.variables) &&
        Objects.equals(this.version, v1beta1ClusterSpecTopology.version) &&
        Objects.equals(this.workers, v1beta1ClusterSpecTopology.workers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyClass, controlPlane, rolloutAfter, variables, version, workers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterSpecTopology {\n");
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("    controlPlane: ").append(toIndentedString(controlPlane)).append("\n");
    sb.append("    rolloutAfter: ").append(toIndentedString(rolloutAfter)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    workers: ").append(toIndentedString(workers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("class");
    openapiFields.add("controlPlane");
    openapiFields.add("rolloutAfter");
    openapiFields.add("variables");
    openapiFields.add("version");
    openapiFields.add("workers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("class");
    openapiRequiredFields.add("version");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterSpecTopology
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterSpecTopology.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterSpecTopology is not found in the empty JSON string", V1beta1ClusterSpecTopology.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterSpecTopology.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterSpecTopology` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1beta1ClusterSpecTopology.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("class").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `class` to be a primitive type in the JSON string but got `%s`", jsonObj.get("class").toString()));
      }
      // validate the optional field `controlPlane`
      if (jsonObj.get("controlPlane") != null && !jsonObj.get("controlPlane").isJsonNull()) {
        V1beta1ClusterSpecTopologyControlPlane.validateJsonElement(jsonObj.get("controlPlane"));
      }
      if (jsonObj.get("variables") != null && !jsonObj.get("variables").isJsonNull()) {
        JsonArray jsonArrayvariables = jsonObj.getAsJsonArray("variables");
        if (jsonArrayvariables != null) {
          // ensure the json data is an array
          if (!jsonObj.get("variables").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `variables` to be an array in the JSON string but got `%s`", jsonObj.get("variables").toString()));
          }

          // validate the optional field `variables` (array)
          for (int i = 0; i < jsonArrayvariables.size(); i++) {
            V1beta1ClusterSpecTopologyControlPlaneVariablesOverridesInner.validateJsonElement(jsonArrayvariables.get(i));
          };
        }
      }
      if (!jsonObj.get("version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("version").toString()));
      }
      // validate the optional field `workers`
      if (jsonObj.get("workers") != null && !jsonObj.get("workers").isJsonNull()) {
        V1beta1ClusterSpecTopologyWorkers.validateJsonElement(jsonObj.get("workers"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterSpecTopology.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterSpecTopology' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterSpecTopology> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterSpecTopology.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterSpecTopology>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterSpecTopology value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterSpecTopology read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterSpecTopology given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterSpecTopology
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterSpecTopology
  */
  public static V1beta1ClusterSpecTopology fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterSpecTopology.class);
  }

 /**
  * Convert an instance of V1beta1ClusterSpecTopology to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

