/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.x_k8s.cluster.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * ValueFrom defines the value of the patch. Note: Either Value or ValueFrom is required for add and replace operations. Only one of them is allowed to be set at the same time.
 */
@ApiModel(description = "ValueFrom defines the value of the patch. Note: Either Value or ValueFrom is required for add and replace operations. Only one of them is allowed to be set at the same time.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T10:19:01.466108Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom {
  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  private String template;

  public static final String SERIALIZED_NAME_VARIABLE = "variable";
  @SerializedName(SERIALIZED_NAME_VARIABLE)
  private String variable;

  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom() {
  }

  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom template(String template) {
    this.template = template;
    return this;
  }

   /**
   * Template is the Go template to be used to calculate the value. A template can reference variables defined in .spec.variables and builtin variables. Note: The template must evaluate to a valid YAML or JSON value.
   * @return template
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Template is the Go template to be used to calculate the value. A template can reference variables defined in .spec.variables and builtin variables. Note: The template must evaluate to a valid YAML or JSON value.")
  public String getTemplate() {
    return template;
  }

  public void setTemplate(String template) {
    this.template = template;
  }


  public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom variable(String variable) {
    this.variable = variable;
    return this;
  }

   /**
   * Variable is the variable to be used as value. Variable can be one of the variables defined in .spec.variables or a builtin variable.
   * @return variable
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Variable is the variable to be used as value. Variable can be one of the variables defined in .spec.variables or a builtin variable.")
  public String getVariable() {
    return variable;
  }

  public void setVariable(String variable) {
    this.variable = variable;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom v1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom = (V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom) o;
    return Objects.equals(this.template, v1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom.template) &&
        Objects.equals(this.variable, v1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom.variable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(template, variable);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom {\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    variable: ").append(toIndentedString(variable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("template");
    openapiFields.add("variable");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom is not found in the empty JSON string", V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("template") != null && !jsonObj.get("template").isJsonNull()) && !jsonObj.get("template").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `template` to be a primitive type in the JSON string but got `%s`", jsonObj.get("template").toString()));
      }
      if ((jsonObj.get("variable") != null && !jsonObj.get("variable").isJsonNull()) && !jsonObj.get("variable").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `variable` to be a primitive type in the JSON string but got `%s`", jsonObj.get("variable").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom>() {
           @Override
           public void write(JsonWriter out, V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom
  * @throws IOException if the JSON string is invalid with respect to V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom
  */
  public static V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom.class);
  }

 /**
  * Convert an instance of V1beta1ClusterClassSpecPatchesInnerDefinitionsInnerJsonPatchesInnerValueFrom to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

