/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.cns.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.cns.models.V1alpha1StoragePoolStatusCapacity;
import com.vmware.cns.models.V1alpha1StoragePoolStatusError;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * StoragePoolStatus defines the observed state of StoragePool
 */
@ApiModel(description = "StoragePoolStatus defines the observed state of StoragePool")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T09:29:11.173219Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1alpha1StoragePoolStatus {
  public static final String SERIALIZED_NAME_ACCESSIBLE_NODES = "accessibleNodes";
  @SerializedName(SERIALIZED_NAME_ACCESSIBLE_NODES)
  private List<String> accessibleNodes = new ArrayList<>();

  public static final String SERIALIZED_NAME_CAPACITY = "capacity";
  @SerializedName(SERIALIZED_NAME_CAPACITY)
  private V1alpha1StoragePoolStatusCapacity capacity;

  public static final String SERIALIZED_NAME_COMPATIBLE_STORAGE_CLASSES = "compatibleStorageClasses";
  @SerializedName(SERIALIZED_NAME_COMPATIBLE_STORAGE_CLASSES)
  private List<String> compatibleStorageClasses = new ArrayList<>();

  public static final String SERIALIZED_NAME_DISK_DECOMM = "diskDecomm";
  @SerializedName(SERIALIZED_NAME_DISK_DECOMM)
  private Map<String, String> diskDecomm = new HashMap<>();

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private V1alpha1StoragePoolStatusError error;

  public V1alpha1StoragePoolStatus() {
  }

  public V1alpha1StoragePoolStatus accessibleNodes(List<String> accessibleNodes) {
    this.accessibleNodes = accessibleNodes;
    return this;
  }

  public V1alpha1StoragePoolStatus addAccessibleNodesItem(String accessibleNodesItem) {
    if (this.accessibleNodes == null) {
      this.accessibleNodes = new ArrayList<>();
    }
    this.accessibleNodes.add(accessibleNodesItem);
    return this;
  }

   /**
   * Nodes the storage pool has access to
   * @return accessibleNodes
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Nodes the storage pool has access to")
  public List<String> getAccessibleNodes() {
    return accessibleNodes;
  }

  public void setAccessibleNodes(List<String> accessibleNodes) {
    this.accessibleNodes = accessibleNodes;
  }


  public V1alpha1StoragePoolStatus capacity(V1alpha1StoragePoolStatusCapacity capacity) {
    this.capacity = capacity;
    return this;
  }

   /**
   * Get capacity
   * @return capacity
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1alpha1StoragePoolStatusCapacity getCapacity() {
    return capacity;
  }

  public void setCapacity(V1alpha1StoragePoolStatusCapacity capacity) {
    this.capacity = capacity;
  }


  public V1alpha1StoragePoolStatus compatibleStorageClasses(List<String> compatibleStorageClasses) {
    this.compatibleStorageClasses = compatibleStorageClasses;
    return this;
  }

  public V1alpha1StoragePoolStatus addCompatibleStorageClassesItem(String compatibleStorageClassesItem) {
    if (this.compatibleStorageClasses == null) {
      this.compatibleStorageClasses = new ArrayList<>();
    }
    this.compatibleStorageClasses.add(compatibleStorageClassesItem);
    return this;
  }

   /**
   * StorageClasses that can be used with this storage pool
   * @return compatibleStorageClasses
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "StorageClasses that can be used with this storage pool")
  public List<String> getCompatibleStorageClasses() {
    return compatibleStorageClasses;
  }

  public void setCompatibleStorageClasses(List<String> compatibleStorageClasses) {
    this.compatibleStorageClasses = compatibleStorageClasses;
  }


  public V1alpha1StoragePoolStatus diskDecomm(Map<String, String> diskDecomm) {
    this.diskDecomm = diskDecomm;
    return this;
  }

  public V1alpha1StoragePoolStatus putDiskDecommItem(String key, String diskDecommItem) {
    if (this.diskDecomm == null) {
      this.diskDecomm = new HashMap<>();
    }
    this.diskDecomm.put(key, diskDecommItem);
    return this;
  }

   /**
   * DiskDecomm indicates the status of disk decommission for the given storagepool
   * @return diskDecomm
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "DiskDecomm indicates the status of disk decommission for the given storagepool")
  public Map<String, String> getDiskDecomm() {
    return diskDecomm;
  }

  public void setDiskDecomm(Map<String, String> diskDecomm) {
    this.diskDecomm = diskDecomm;
  }


  public V1alpha1StoragePoolStatus error(V1alpha1StoragePoolStatusError error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1alpha1StoragePoolStatusError getError() {
    return error;
  }

  public void setError(V1alpha1StoragePoolStatusError error) {
    this.error = error;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1StoragePoolStatus v1alpha1StoragePoolStatus = (V1alpha1StoragePoolStatus) o;
    return Objects.equals(this.accessibleNodes, v1alpha1StoragePoolStatus.accessibleNodes) &&
        Objects.equals(this.capacity, v1alpha1StoragePoolStatus.capacity) &&
        Objects.equals(this.compatibleStorageClasses, v1alpha1StoragePoolStatus.compatibleStorageClasses) &&
        Objects.equals(this.diskDecomm, v1alpha1StoragePoolStatus.diskDecomm) &&
        Objects.equals(this.error, v1alpha1StoragePoolStatus.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessibleNodes, capacity, compatibleStorageClasses, diskDecomm, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1StoragePoolStatus {\n");
    sb.append("    accessibleNodes: ").append(toIndentedString(accessibleNodes)).append("\n");
    sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
    sb.append("    compatibleStorageClasses: ").append(toIndentedString(compatibleStorageClasses)).append("\n");
    sb.append("    diskDecomm: ").append(toIndentedString(diskDecomm)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("accessibleNodes");
    openapiFields.add("capacity");
    openapiFields.add("compatibleStorageClasses");
    openapiFields.add("diskDecomm");
    openapiFields.add("error");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1alpha1StoragePoolStatus
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1alpha1StoragePoolStatus.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha1StoragePoolStatus is not found in the empty JSON string", V1alpha1StoragePoolStatus.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1alpha1StoragePoolStatus.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha1StoragePoolStatus` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("accessibleNodes") != null && !jsonObj.get("accessibleNodes").isJsonNull() && !jsonObj.get("accessibleNodes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `accessibleNodes` to be an array in the JSON string but got `%s`", jsonObj.get("accessibleNodes").toString()));
      }
      // validate the optional field `capacity`
      if (jsonObj.get("capacity") != null && !jsonObj.get("capacity").isJsonNull()) {
        V1alpha1StoragePoolStatusCapacity.validateJsonElement(jsonObj.get("capacity"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("compatibleStorageClasses") != null && !jsonObj.get("compatibleStorageClasses").isJsonNull() && !jsonObj.get("compatibleStorageClasses").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `compatibleStorageClasses` to be an array in the JSON string but got `%s`", jsonObj.get("compatibleStorageClasses").toString()));
      }
      // validate the optional field `error`
      if (jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) {
        V1alpha1StoragePoolStatusError.validateJsonElement(jsonObj.get("error"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha1StoragePoolStatus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha1StoragePoolStatus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha1StoragePoolStatus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha1StoragePoolStatus.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha1StoragePoolStatus>() {
           @Override
           public void write(JsonWriter out, V1alpha1StoragePoolStatus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha1StoragePoolStatus read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha1StoragePoolStatus given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha1StoragePoolStatus
  * @throws IOException if the JSON string is invalid with respect to V1alpha1StoragePoolStatus
  */
  public static V1alpha1StoragePoolStatus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1alpha1StoragePoolStatus.class);
  }

 /**
  * Convert an instance of V1alpha1StoragePoolStatus to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

