/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.cns.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * CnsFileAccessConfigStatus defines the observed state of CnsFileAccessConfig
 */
@ApiModel(description = "CnsFileAccessConfigStatus defines the observed state of CnsFileAccessConfig")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T09:29:11.173219Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1alpha1CnsFileAccessConfigStatus {
  public static final String SERIALIZED_NAME_ACCESS_POINTS = "accessPoints";
  @SerializedName(SERIALIZED_NAME_ACCESS_POINTS)
  private Map<String, String> accessPoints = new HashMap<>();

  public static final String SERIALIZED_NAME_DONE = "done";
  @SerializedName(SERIALIZED_NAME_DONE)
  private Boolean done;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private String error;

  public V1alpha1CnsFileAccessConfigStatus() {
  }

  public V1alpha1CnsFileAccessConfigStatus accessPoints(Map<String, String> accessPoints) {
    this.accessPoints = accessPoints;
    return this;
  }

  public V1alpha1CnsFileAccessConfigStatus putAccessPointsItem(String key, String accessPointsItem) {
    if (this.accessPoints == null) {
      this.accessPoints = new HashMap<>();
    }
    this.accessPoints.put(key, accessPointsItem);
    return this;
  }

   /**
   * Access points per protocol supported by the volume. This field must only be set by the entity completing the config operation, i.e. the CNS Operator. AccessPoints field will only be set when the CnsFileAccessConfig.Status.Done field is set to true.
   * @return accessPoints
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Access points per protocol supported by the volume. This field must only be set by the entity completing the config operation, i.e. the CNS Operator. AccessPoints field will only be set when the CnsFileAccessConfig.Status.Done field is set to true.")
  public Map<String, String> getAccessPoints() {
    return accessPoints;
  }

  public void setAccessPoints(Map<String, String> accessPoints) {
    this.accessPoints = accessPoints;
  }


  public V1alpha1CnsFileAccessConfigStatus done(Boolean done) {
    this.done = done;
    return this;
  }

   /**
   * Done indicates whether the ACL has been configured on file volume. This field must only be set by the entity completing the register operation, i.e. the CNS Operator.
   * @return done
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Done indicates whether the ACL has been configured on file volume. This field must only be set by the entity completing the register operation, i.e. the CNS Operator.")
  public Boolean getDone() {
    return done;
  }

  public void setDone(Boolean done) {
    this.done = done;
  }


  public V1alpha1CnsFileAccessConfigStatus error(String error) {
    this.error = error;
    return this;
  }

   /**
   * The last error encountered during file volume config operation, if any This field must only be set by the entity completing the config operation, i.e. the CNS Operator.
   * @return error
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "The last error encountered during file volume config operation, if any This field must only be set by the entity completing the config operation, i.e. the CNS Operator.")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CnsFileAccessConfigStatus v1alpha1CnsFileAccessConfigStatus = (V1alpha1CnsFileAccessConfigStatus) o;
    return Objects.equals(this.accessPoints, v1alpha1CnsFileAccessConfigStatus.accessPoints) &&
        Objects.equals(this.done, v1alpha1CnsFileAccessConfigStatus.done) &&
        Objects.equals(this.error, v1alpha1CnsFileAccessConfigStatus.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessPoints, done, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CnsFileAccessConfigStatus {\n");
    sb.append("    accessPoints: ").append(toIndentedString(accessPoints)).append("\n");
    sb.append("    done: ").append(toIndentedString(done)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("accessPoints");
    openapiFields.add("done");
    openapiFields.add("error");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1alpha1CnsFileAccessConfigStatus
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1alpha1CnsFileAccessConfigStatus.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha1CnsFileAccessConfigStatus is not found in the empty JSON string", V1alpha1CnsFileAccessConfigStatus.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1alpha1CnsFileAccessConfigStatus.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha1CnsFileAccessConfigStatus` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) && !jsonObj.get("error").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `error` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha1CnsFileAccessConfigStatus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha1CnsFileAccessConfigStatus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha1CnsFileAccessConfigStatus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha1CnsFileAccessConfigStatus.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha1CnsFileAccessConfigStatus>() {
           @Override
           public void write(JsonWriter out, V1alpha1CnsFileAccessConfigStatus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha1CnsFileAccessConfigStatus read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha1CnsFileAccessConfigStatus given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha1CnsFileAccessConfigStatus
  * @throws IOException if the JSON string is invalid with respect to V1alpha1CnsFileAccessConfigStatus
  */
  public static V1alpha1CnsFileAccessConfigStatus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1alpha1CnsFileAccessConfigStatus.class);
  }

 /**
  * Convert an instance of V1alpha1CnsFileAccessConfigStatus to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

