/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.cns.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * Storage usage details per storage object type for given storage policy
 */
@ApiModel(description = "Storage usage details per storage object type for given storage policy")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T09:29:11.173219Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1alpha1StoragePolicyUsageStatusQuotaUsage {
  public static final String SERIALIZED_NAME_RESERVED = "reserved";
  @SerializedName(SERIALIZED_NAME_RESERVED)
  private Object reserved;

  public static final String SERIALIZED_NAME_USED = "used";
  @SerializedName(SERIALIZED_NAME_USED)
  private Object used;

  public V1alpha1StoragePolicyUsageStatusQuotaUsage() {
  }

  public V1alpha1StoragePolicyUsageStatusQuotaUsage reserved(Object reserved) {
    this.reserved = reserved;
    return this;
  }

   /**
   * Storage quota that is reserved for storage resource(s) that are being provisioned
   * @return reserved
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Storage quota that is reserved for storage resource(s) that are being provisioned")
  public Object getReserved() {
    return reserved;
  }

  public void setReserved(Object reserved) {
    this.reserved = reserved;
  }


  public V1alpha1StoragePolicyUsageStatusQuotaUsage used(Object used) {
    this.used = used;
    return this;
  }

   /**
   * Storage quota that is already used by storage resource(s) that have been provisioned
   * @return used
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Storage quota that is already used by storage resource(s) that have been provisioned")
  public Object getUsed() {
    return used;
  }

  public void setUsed(Object used) {
    this.used = used;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1StoragePolicyUsageStatusQuotaUsage v1alpha1StoragePolicyUsageStatusQuotaUsage = (V1alpha1StoragePolicyUsageStatusQuotaUsage) o;
    return Objects.equals(this.reserved, v1alpha1StoragePolicyUsageStatusQuotaUsage.reserved) &&
        Objects.equals(this.used, v1alpha1StoragePolicyUsageStatusQuotaUsage.used);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reserved, used);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1StoragePolicyUsageStatusQuotaUsage {\n");
    sb.append("    reserved: ").append(toIndentedString(reserved)).append("\n");
    sb.append("    used: ").append(toIndentedString(used)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("reserved");
    openapiFields.add("used");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1alpha1StoragePolicyUsageStatusQuotaUsage
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1alpha1StoragePolicyUsageStatusQuotaUsage.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha1StoragePolicyUsageStatusQuotaUsage is not found in the empty JSON string", V1alpha1StoragePolicyUsageStatusQuotaUsage.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1alpha1StoragePolicyUsageStatusQuotaUsage.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha1StoragePolicyUsageStatusQuotaUsage` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha1StoragePolicyUsageStatusQuotaUsage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha1StoragePolicyUsageStatusQuotaUsage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha1StoragePolicyUsageStatusQuotaUsage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha1StoragePolicyUsageStatusQuotaUsage.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha1StoragePolicyUsageStatusQuotaUsage>() {
           @Override
           public void write(JsonWriter out, V1alpha1StoragePolicyUsageStatusQuotaUsage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha1StoragePolicyUsageStatusQuotaUsage read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha1StoragePolicyUsageStatusQuotaUsage given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha1StoragePolicyUsageStatusQuotaUsage
  * @throws IOException if the JSON string is invalid with respect to V1alpha1StoragePolicyUsageStatusQuotaUsage
  */
  public static V1alpha1StoragePolicyUsageStatusQuotaUsage fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1alpha1StoragePolicyUsageStatusQuotaUsage.class);
  }

 /**
  * Convert an instance of V1alpha1StoragePolicyUsageStatusQuotaUsage to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

