/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.cns.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * CnsFileAccessConfigSpec defines the desired state of CnsFileAccessConfig
 */
@ApiModel(description = "CnsFileAccessConfigSpec defines the desired state of CnsFileAccessConfig")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T09:29:11.173219Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1alpha1CnsFileAccessConfigSpec {
  public static final String SERIALIZED_NAME_PVC_NAME = "pvcName";
  @SerializedName(SERIALIZED_NAME_PVC_NAME)
  private String pvcName;

  public static final String SERIALIZED_NAME_VM_NAME = "vmName";
  @SerializedName(SERIALIZED_NAME_VM_NAME)
  private String vmName;

  public V1alpha1CnsFileAccessConfigSpec() {
  }

  public V1alpha1CnsFileAccessConfigSpec pvcName(String pvcName) {
    this.pvcName = pvcName;
    return this;
  }

   /**
   * PvcName indicates the name of the PVC on the supervisor Cluster. This is guaranteed to be unique in Supervisor cluster.
   * @return pvcName
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "PvcName indicates the name of the PVC on the supervisor Cluster. This is guaranteed to be unique in Supervisor cluster.")
  public String getPvcName() {
    return pvcName;
  }

  public void setPvcName(String pvcName) {
    this.pvcName = pvcName;
  }


  public V1alpha1CnsFileAccessConfigSpec vmName(String vmName) {
    this.vmName = vmName;
    return this;
  }

   /**
   * VmName is the name of VirtualMachine instance on SV cluster Support for PodVm will be added in the near future and either VMName or PodVMName needs to be set.
   * @return vmName
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "VmName is the name of VirtualMachine instance on SV cluster Support for PodVm will be added in the near future and either VMName or PodVMName needs to be set.")
  public String getVmName() {
    return vmName;
  }

  public void setVmName(String vmName) {
    this.vmName = vmName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CnsFileAccessConfigSpec v1alpha1CnsFileAccessConfigSpec = (V1alpha1CnsFileAccessConfigSpec) o;
    return Objects.equals(this.pvcName, v1alpha1CnsFileAccessConfigSpec.pvcName) &&
        Objects.equals(this.vmName, v1alpha1CnsFileAccessConfigSpec.vmName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pvcName, vmName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CnsFileAccessConfigSpec {\n");
    sb.append("    pvcName: ").append(toIndentedString(pvcName)).append("\n");
    sb.append("    vmName: ").append(toIndentedString(vmName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("pvcName");
    openapiFields.add("vmName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("pvcName");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1alpha1CnsFileAccessConfigSpec
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1alpha1CnsFileAccessConfigSpec.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha1CnsFileAccessConfigSpec is not found in the empty JSON string", V1alpha1CnsFileAccessConfigSpec.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1alpha1CnsFileAccessConfigSpec.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha1CnsFileAccessConfigSpec` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1alpha1CnsFileAccessConfigSpec.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("pvcName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pvcName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pvcName").toString()));
      }
      if ((jsonObj.get("vmName") != null && !jsonObj.get("vmName").isJsonNull()) && !jsonObj.get("vmName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vmName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vmName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha1CnsFileAccessConfigSpec.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha1CnsFileAccessConfigSpec' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha1CnsFileAccessConfigSpec> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha1CnsFileAccessConfigSpec.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha1CnsFileAccessConfigSpec>() {
           @Override
           public void write(JsonWriter out, V1alpha1CnsFileAccessConfigSpec value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha1CnsFileAccessConfigSpec read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha1CnsFileAccessConfigSpec given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha1CnsFileAccessConfigSpec
  * @throws IOException if the JSON string is invalid with respect to V1alpha1CnsFileAccessConfigSpec
  */
  public static V1alpha1CnsFileAccessConfigSpec fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1alpha1CnsFileAccessConfigSpec.class);
  }

 /**
  * Convert an instance of V1alpha1CnsFileAccessConfigSpec to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

