/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.cns.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * CnsRegisterVolumeSpec defines the desired state of CnsRegisterVolume
 */
@ApiModel(description = "CnsRegisterVolumeSpec defines the desired state of CnsRegisterVolume")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T09:29:11.173219Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1alpha1CnsRegisterVolumeSpec {
  public static final String SERIALIZED_NAME_ACCESS_MODE = "accessMode";
  @SerializedName(SERIALIZED_NAME_ACCESS_MODE)
  private String accessMode;

  public static final String SERIALIZED_NAME_DISK_U_R_L_PATH = "diskURLPath";
  @SerializedName(SERIALIZED_NAME_DISK_U_R_L_PATH)
  private String diskURLPath;

  public static final String SERIALIZED_NAME_PVC_NAME = "pvcName";
  @SerializedName(SERIALIZED_NAME_PVC_NAME)
  private String pvcName;

  public static final String SERIALIZED_NAME_VOLUME_I_D = "volumeID";
  @SerializedName(SERIALIZED_NAME_VOLUME_I_D)
  private String volumeID;

  public V1alpha1CnsRegisterVolumeSpec() {
  }

  public V1alpha1CnsRegisterVolumeSpec accessMode(String accessMode) {
    this.accessMode = accessMode;
    return this;
  }

   /**
   * AccessMode contains the actual access mode the volume backing the CnsRegisterVolume has. AccessMode must be specified if VolumeID is specified.
   * @return accessMode
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "AccessMode contains the actual access mode the volume backing the CnsRegisterVolume has. AccessMode must be specified if VolumeID is specified.")
  public String getAccessMode() {
    return accessMode;
  }

  public void setAccessMode(String accessMode) {
    this.accessMode = accessMode;
  }


  public V1alpha1CnsRegisterVolumeSpec diskURLPath(String diskURLPath) {
    this.diskURLPath = diskURLPath;
    return this;
  }

   /**
   * DiskUrlPath is URL path to an existing block volume to be imported into Project Pacific cluster. VolumeID and DiskUrlPath cannot be specified together. DiskUrlPath is explicitly used for block volumes. AccessMode need not be specified and will be defaulted to \&quot;ReadWriteOnce\&quot;. This field must be in the following format: Format: https://&lt;vc_ip&gt;/folder/&lt;vm_vmdk_path&gt;?dcPath&#x3D;&lt;datacenterName&gt;&amp;dsName&#x3D;&lt;datastoreName&gt; Ex: https://10.192.255.221/folder/34a9c05d-5f03-e254-e692-02004479cb91/        vm2_1.vmdk?dcPath&#x3D;Datacenter-1&amp;dsName&#x3D;vsanDatastore This is for a 34a9c05d-5f03-e254-e692-02004479cb91/vm2_1.vmdk file under datacenter \&quot;Datacenter-1\&quot; and datastore \&quot;vsanDatastore\&quot;.
   * @return diskURLPath
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "DiskUrlPath is URL path to an existing block volume to be imported into Project Pacific cluster. VolumeID and DiskUrlPath cannot be specified together. DiskUrlPath is explicitly used for block volumes. AccessMode need not be specified and will be defaulted to \"ReadWriteOnce\". This field must be in the following format: Format: https://<vc_ip>/folder/<vm_vmdk_path>?dcPath=<datacenterName>&dsName=<datastoreName> Ex: https://10.192.255.221/folder/34a9c05d-5f03-e254-e692-02004479cb91/        vm2_1.vmdk?dcPath=Datacenter-1&dsName=vsanDatastore This is for a 34a9c05d-5f03-e254-e692-02004479cb91/vm2_1.vmdk file under datacenter \"Datacenter-1\" and datastore \"vsanDatastore\".")
  public String getDiskURLPath() {
    return diskURLPath;
  }

  public void setDiskURLPath(String diskURLPath) {
    this.diskURLPath = diskURLPath;
  }


  public V1alpha1CnsRegisterVolumeSpec pvcName(String pvcName) {
    this.pvcName = pvcName;
    return this;
  }

   /**
   * Name of the PVC
   * @return pvcName
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Name of the PVC")
  public String getPvcName() {
    return pvcName;
  }

  public void setPvcName(String pvcName) {
    this.pvcName = pvcName;
  }


  public V1alpha1CnsRegisterVolumeSpec volumeID(String volumeID) {
    this.volumeID = volumeID;
    return this;
  }

   /**
   * VolumeID indicates an existing vsphere volume to be imported into Project Pacific cluster. If the AccessMode is \&quot;ReadWriteMany\&quot; or \&quot;ReadOnlyMany\&quot;, then this VolumeID can be either an existing FileShare (or) CNS file volume backed FileShare. If the AccessMode is \&quot;ReadWriteOnce\&quot;, then this VolumeID can be either an existing FCD (or) a CNS backed FCD. VolumeID and DiskUrlPath cannot be specified together.
   * @return volumeID
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "VolumeID indicates an existing vsphere volume to be imported into Project Pacific cluster. If the AccessMode is \"ReadWriteMany\" or \"ReadOnlyMany\", then this VolumeID can be either an existing FileShare (or) CNS file volume backed FileShare. If the AccessMode is \"ReadWriteOnce\", then this VolumeID can be either an existing FCD (or) a CNS backed FCD. VolumeID and DiskUrlPath cannot be specified together.")
  public String getVolumeID() {
    return volumeID;
  }

  public void setVolumeID(String volumeID) {
    this.volumeID = volumeID;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CnsRegisterVolumeSpec v1alpha1CnsRegisterVolumeSpec = (V1alpha1CnsRegisterVolumeSpec) o;
    return Objects.equals(this.accessMode, v1alpha1CnsRegisterVolumeSpec.accessMode) &&
        Objects.equals(this.diskURLPath, v1alpha1CnsRegisterVolumeSpec.diskURLPath) &&
        Objects.equals(this.pvcName, v1alpha1CnsRegisterVolumeSpec.pvcName) &&
        Objects.equals(this.volumeID, v1alpha1CnsRegisterVolumeSpec.volumeID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessMode, diskURLPath, pvcName, volumeID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CnsRegisterVolumeSpec {\n");
    sb.append("    accessMode: ").append(toIndentedString(accessMode)).append("\n");
    sb.append("    diskURLPath: ").append(toIndentedString(diskURLPath)).append("\n");
    sb.append("    pvcName: ").append(toIndentedString(pvcName)).append("\n");
    sb.append("    volumeID: ").append(toIndentedString(volumeID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("accessMode");
    openapiFields.add("diskURLPath");
    openapiFields.add("pvcName");
    openapiFields.add("volumeID");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("pvcName");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1alpha1CnsRegisterVolumeSpec
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1alpha1CnsRegisterVolumeSpec.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha1CnsRegisterVolumeSpec is not found in the empty JSON string", V1alpha1CnsRegisterVolumeSpec.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1alpha1CnsRegisterVolumeSpec.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha1CnsRegisterVolumeSpec` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1alpha1CnsRegisterVolumeSpec.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("accessMode") != null && !jsonObj.get("accessMode").isJsonNull()) && !jsonObj.get("accessMode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `accessMode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accessMode").toString()));
      }
      if ((jsonObj.get("diskURLPath") != null && !jsonObj.get("diskURLPath").isJsonNull()) && !jsonObj.get("diskURLPath").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `diskURLPath` to be a primitive type in the JSON string but got `%s`", jsonObj.get("diskURLPath").toString()));
      }
      if (!jsonObj.get("pvcName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pvcName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pvcName").toString()));
      }
      if ((jsonObj.get("volumeID") != null && !jsonObj.get("volumeID").isJsonNull()) && !jsonObj.get("volumeID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `volumeID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("volumeID").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha1CnsRegisterVolumeSpec.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha1CnsRegisterVolumeSpec' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha1CnsRegisterVolumeSpec> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha1CnsRegisterVolumeSpec.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha1CnsRegisterVolumeSpec>() {
           @Override
           public void write(JsonWriter out, V1alpha1CnsRegisterVolumeSpec value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha1CnsRegisterVolumeSpec read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha1CnsRegisterVolumeSpec given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha1CnsRegisterVolumeSpec
  * @throws IOException if the JSON string is invalid with respect to V1alpha1CnsRegisterVolumeSpec
  */
  public static V1alpha1CnsRegisterVolumeSpec fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1alpha1CnsRegisterVolumeSpec.class);
  }

 /**
  * Convert an instance of V1alpha1CnsRegisterVolumeSpec to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

