/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.cns.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * CnsNodeVmAttachmentStatus defines the observed state of CnsNodeVmAttachment
 */
@ApiModel(description = "CnsNodeVmAttachmentStatus defines the observed state of CnsNodeVmAttachment")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T09:29:11.173219Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1alpha1CnsNodeVmAttachmentStatus {
  public static final String SERIALIZED_NAME_ATTACHED = "attached";
  @SerializedName(SERIALIZED_NAME_ATTACHED)
  private Boolean attached;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private String error;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Map<String, String> metadata = new HashMap<>();

  public V1alpha1CnsNodeVmAttachmentStatus() {
  }

  public V1alpha1CnsNodeVmAttachmentStatus attached(Boolean attached) {
    this.attached = attached;
    return this;
  }

   /**
   * Indicates the volume is successfully attached. This field must only be set by the entity completing the attach operation, i.e. the CNS Operator.
   * @return attached
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Indicates the volume is successfully attached. This field must only be set by the entity completing the attach operation, i.e. the CNS Operator.")
  public Boolean getAttached() {
    return attached;
  }

  public void setAttached(Boolean attached) {
    this.attached = attached;
  }


  public V1alpha1CnsNodeVmAttachmentStatus error(String error) {
    this.error = error;
    return this;
  }

   /**
   * The last error encountered during attach/detach operation, if any. This field must only be set by the entity completing the attach operation, i.e. the CNS Operator.
   * @return error
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "The last error encountered during attach/detach operation, if any. This field must only be set by the entity completing the attach operation, i.e. the CNS Operator.")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }


  public V1alpha1CnsNodeVmAttachmentStatus metadata(Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  public V1alpha1CnsNodeVmAttachmentStatus putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Before successful attach, this field is populated with CNS volume ID. Upon successful attach, this field is populated with any information returned by the attach operation. This field must only be set by the entity completing the attach operation, i.e. the CNS Operator
   * @return metadata
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Before successful attach, this field is populated with CNS volume ID. Upon successful attach, this field is populated with any information returned by the attach operation. This field must only be set by the entity completing the attach operation, i.e. the CNS Operator")
  public Map<String, String> getMetadata() {
    return metadata;
  }

  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CnsNodeVmAttachmentStatus v1alpha1CnsNodeVmAttachmentStatus = (V1alpha1CnsNodeVmAttachmentStatus) o;
    return Objects.equals(this.attached, v1alpha1CnsNodeVmAttachmentStatus.attached) &&
        Objects.equals(this.error, v1alpha1CnsNodeVmAttachmentStatus.error) &&
        Objects.equals(this.metadata, v1alpha1CnsNodeVmAttachmentStatus.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attached, error, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CnsNodeVmAttachmentStatus {\n");
    sb.append("    attached: ").append(toIndentedString(attached)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("attached");
    openapiFields.add("error");
    openapiFields.add("metadata");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("attached");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1alpha1CnsNodeVmAttachmentStatus
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1alpha1CnsNodeVmAttachmentStatus.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha1CnsNodeVmAttachmentStatus is not found in the empty JSON string", V1alpha1CnsNodeVmAttachmentStatus.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1alpha1CnsNodeVmAttachmentStatus.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha1CnsNodeVmAttachmentStatus` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1alpha1CnsNodeVmAttachmentStatus.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) && !jsonObj.get("error").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `error` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha1CnsNodeVmAttachmentStatus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha1CnsNodeVmAttachmentStatus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha1CnsNodeVmAttachmentStatus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha1CnsNodeVmAttachmentStatus.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha1CnsNodeVmAttachmentStatus>() {
           @Override
           public void write(JsonWriter out, V1alpha1CnsNodeVmAttachmentStatus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha1CnsNodeVmAttachmentStatus read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha1CnsNodeVmAttachmentStatus given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha1CnsNodeVmAttachmentStatus
  * @throws IOException if the JSON string is invalid with respect to V1alpha1CnsNodeVmAttachmentStatus
  */
  public static V1alpha1CnsNodeVmAttachmentStatus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1alpha1CnsNodeVmAttachmentStatus.class);
  }

 /**
  * Convert an instance of V1alpha1CnsNodeVmAttachmentStatus to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

