/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.cns.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * StoragePolicyUsageSpec defines the desired state of StoragePolicyUsage
 */
@ApiModel(description = "StoragePolicyUsageSpec defines the desired state of StoragePolicyUsage")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T09:29:11.173219Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1alpha2StoragePolicyUsageSpec {
  public static final String SERIALIZED_NAME_CA_BUNDLE = "caBundle";
  @SerializedName(SERIALIZED_NAME_CA_BUNDLE)
  private byte[] caBundle;

  public static final String SERIALIZED_NAME_RESOURCE_API_GROUP = "resourceApiGroup";
  @SerializedName(SERIALIZED_NAME_RESOURCE_API_GROUP)
  private String resourceApiGroup;

  public static final String SERIALIZED_NAME_RESOURCE_EXTENSION_NAME = "resourceExtensionName";
  @SerializedName(SERIALIZED_NAME_RESOURCE_EXTENSION_NAME)
  private String resourceExtensionName;

  public static final String SERIALIZED_NAME_RESOURCE_EXTENSION_NAMESPACE = "resourceExtensionNamespace";
  @SerializedName(SERIALIZED_NAME_RESOURCE_EXTENSION_NAMESPACE)
  private String resourceExtensionNamespace;

  public static final String SERIALIZED_NAME_RESOURCE_KIND = "resourceKind";
  @SerializedName(SERIALIZED_NAME_RESOURCE_KIND)
  private String resourceKind;

  public static final String SERIALIZED_NAME_STORAGE_CLASS_NAME = "storageClassName";
  @SerializedName(SERIALIZED_NAME_STORAGE_CLASS_NAME)
  private String storageClassName;

  public static final String SERIALIZED_NAME_STORAGE_POLICY_ID = "storagePolicyId";
  @SerializedName(SERIALIZED_NAME_STORAGE_POLICY_ID)
  private String storagePolicyId;

  public V1alpha2StoragePolicyUsageSpec() {
  }

  public V1alpha2StoragePolicyUsageSpec caBundle(byte[] caBundle) {
    this.caBundle = caBundle;
    return this;
  }

   /**
   * caBundle is a PEM encoded CA bundle which will be used to validate the extension service&#39;s server certificate.
   * @return caBundle
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "caBundle is a PEM encoded CA bundle which will be used to validate the extension service's server certificate.")
  public byte[] getCaBundle() {
    return caBundle;
  }

  public void setCaBundle(byte[] caBundle) {
    this.caBundle = caBundle;
  }


  public V1alpha2StoragePolicyUsageSpec resourceApiGroup(String resourceApiGroup) {
    this.resourceApiGroup = resourceApiGroup;
    return this;
  }

   /**
   * APIGroup is the group for the resource being referenced. If it is not specified, the specified ResourceKind must be in the core API group. For resources not in the core API group, this field is required.
   * @return resourceApiGroup
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "APIGroup is the group for the resource being referenced. If it is not specified, the specified ResourceKind must be in the core API group. For resources not in the core API group, this field is required.")
  public String getResourceApiGroup() {
    return resourceApiGroup;
  }

  public void setResourceApiGroup(String resourceApiGroup) {
    this.resourceApiGroup = resourceApiGroup;
  }


  public V1alpha2StoragePolicyUsageSpec resourceExtensionName(String resourceExtensionName) {
    this.resourceExtensionName = resourceExtensionName;
    return this;
  }

   /**
   * Name of service extension for given storage resource type
   * @return resourceExtensionName
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Name of service extension for given storage resource type")
  public String getResourceExtensionName() {
    return resourceExtensionName;
  }

  public void setResourceExtensionName(String resourceExtensionName) {
    this.resourceExtensionName = resourceExtensionName;
  }


  public V1alpha2StoragePolicyUsageSpec resourceExtensionNamespace(String resourceExtensionNamespace) {
    this.resourceExtensionNamespace = resourceExtensionNamespace;
    return this;
  }

   /**
   * Namespace of service extension for given storage resource type
   * @return resourceExtensionNamespace
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Namespace of service extension for given storage resource type")
  public String getResourceExtensionNamespace() {
    return resourceExtensionNamespace;
  }

  public void setResourceExtensionNamespace(String resourceExtensionNamespace) {
    this.resourceExtensionNamespace = resourceExtensionNamespace;
  }


  public V1alpha2StoragePolicyUsageSpec resourceKind(String resourceKind) {
    this.resourceKind = resourceKind;
    return this;
  }

   /**
   * Type of resource being referenced
   * @return resourceKind
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Type of resource being referenced")
  public String getResourceKind() {
    return resourceKind;
  }

  public void setResourceKind(String resourceKind) {
    this.resourceKind = resourceKind;
  }


  public V1alpha2StoragePolicyUsageSpec storageClassName(String storageClassName) {
    this.storageClassName = storageClassName;
    return this;
  }

   /**
   * name of K8S storage class associated with given storage policy
   * @return storageClassName
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "name of K8S storage class associated with given storage policy")
  public String getStorageClassName() {
    return storageClassName;
  }

  public void setStorageClassName(String storageClassName) {
    this.storageClassName = storageClassName;
  }


  public V1alpha2StoragePolicyUsageSpec storagePolicyId(String storagePolicyId) {
    this.storagePolicyId = storagePolicyId;
    return this;
  }

   /**
   * ID of the storage policy
   * @return storagePolicyId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "ID of the storage policy")
  public String getStoragePolicyId() {
    return storagePolicyId;
  }

  public void setStoragePolicyId(String storagePolicyId) {
    this.storagePolicyId = storagePolicyId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha2StoragePolicyUsageSpec v1alpha2StoragePolicyUsageSpec = (V1alpha2StoragePolicyUsageSpec) o;
    return Arrays.equals(this.caBundle, v1alpha2StoragePolicyUsageSpec.caBundle) &&
        Objects.equals(this.resourceApiGroup, v1alpha2StoragePolicyUsageSpec.resourceApiGroup) &&
        Objects.equals(this.resourceExtensionName, v1alpha2StoragePolicyUsageSpec.resourceExtensionName) &&
        Objects.equals(this.resourceExtensionNamespace, v1alpha2StoragePolicyUsageSpec.resourceExtensionNamespace) &&
        Objects.equals(this.resourceKind, v1alpha2StoragePolicyUsageSpec.resourceKind) &&
        Objects.equals(this.storageClassName, v1alpha2StoragePolicyUsageSpec.storageClassName) &&
        Objects.equals(this.storagePolicyId, v1alpha2StoragePolicyUsageSpec.storagePolicyId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Arrays.hashCode(caBundle), resourceApiGroup, resourceExtensionName, resourceExtensionNamespace, resourceKind, storageClassName, storagePolicyId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha2StoragePolicyUsageSpec {\n");
    sb.append("    caBundle: ").append(toIndentedString(caBundle)).append("\n");
    sb.append("    resourceApiGroup: ").append(toIndentedString(resourceApiGroup)).append("\n");
    sb.append("    resourceExtensionName: ").append(toIndentedString(resourceExtensionName)).append("\n");
    sb.append("    resourceExtensionNamespace: ").append(toIndentedString(resourceExtensionNamespace)).append("\n");
    sb.append("    resourceKind: ").append(toIndentedString(resourceKind)).append("\n");
    sb.append("    storageClassName: ").append(toIndentedString(storageClassName)).append("\n");
    sb.append("    storagePolicyId: ").append(toIndentedString(storagePolicyId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("caBundle");
    openapiFields.add("resourceApiGroup");
    openapiFields.add("resourceExtensionName");
    openapiFields.add("resourceExtensionNamespace");
    openapiFields.add("resourceKind");
    openapiFields.add("storageClassName");
    openapiFields.add("storagePolicyId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("resourceExtensionName");
    openapiRequiredFields.add("resourceKind");
    openapiRequiredFields.add("storageClassName");
    openapiRequiredFields.add("storagePolicyId");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1alpha2StoragePolicyUsageSpec
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1alpha2StoragePolicyUsageSpec.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha2StoragePolicyUsageSpec is not found in the empty JSON string", V1alpha2StoragePolicyUsageSpec.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1alpha2StoragePolicyUsageSpec.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha2StoragePolicyUsageSpec` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1alpha2StoragePolicyUsageSpec.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("resourceApiGroup") != null && !jsonObj.get("resourceApiGroup").isJsonNull()) && !jsonObj.get("resourceApiGroup").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `resourceApiGroup` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resourceApiGroup").toString()));
      }
      if (!jsonObj.get("resourceExtensionName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `resourceExtensionName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resourceExtensionName").toString()));
      }
      if ((jsonObj.get("resourceExtensionNamespace") != null && !jsonObj.get("resourceExtensionNamespace").isJsonNull()) && !jsonObj.get("resourceExtensionNamespace").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `resourceExtensionNamespace` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resourceExtensionNamespace").toString()));
      }
      if (!jsonObj.get("resourceKind").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `resourceKind` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resourceKind").toString()));
      }
      if (!jsonObj.get("storageClassName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `storageClassName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("storageClassName").toString()));
      }
      if (!jsonObj.get("storagePolicyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `storagePolicyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("storagePolicyId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha2StoragePolicyUsageSpec.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha2StoragePolicyUsageSpec' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha2StoragePolicyUsageSpec> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha2StoragePolicyUsageSpec.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha2StoragePolicyUsageSpec>() {
           @Override
           public void write(JsonWriter out, V1alpha2StoragePolicyUsageSpec value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha2StoragePolicyUsageSpec read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha2StoragePolicyUsageSpec given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha2StoragePolicyUsageSpec
  * @throws IOException if the JSON string is invalid with respect to V1alpha2StoragePolicyUsageSpec
  */
  public static V1alpha2StoragePolicyUsageSpec fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1alpha2StoragePolicyUsageSpec.class);
  }

 /**
  * Convert an instance of V1alpha2StoragePolicyUsageSpec to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

