/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.cns.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * FeatureState defines the feature name and its state
 */
@ApiModel(description = "FeatureState defines the feature name and its state")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T09:29:11.173219Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner {
  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private Boolean enabled;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner() {
  }

  public V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Enabled is set to true when feature is enabled, else it is set to false
   * @return enabled
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Enabled is set to true when feature is enabled, else it is set to false")
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name is the unique identifier of the feature, this must be unique
   * @return name
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Name is the unique identifier of the feature, this must be unique")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner v1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner = (V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner) o;
    return Objects.equals(this.enabled, v1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner.enabled) &&
        Objects.equals(this.name, v1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner {\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("enabled");
    openapiFields.add("name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("enabled");
    openapiRequiredFields.add("name");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner is not found in the empty JSON string", V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner>() {
           @Override
           public void write(JsonWriter out, V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner
  * @throws IOException if the JSON string is invalid with respect to V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner
  */
  public static V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner.class);
  }

 /**
  * Convert an instance of V1alpha1CnsCsiSvFeatureStatesSpecFeatureStatesInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

