/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.k8s.storage.snapshot.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.k8s.storage.snapshot.models.V1VolumeSnapshotContentStatusError;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * status represents the current information of a snapshot.
 */
@ApiModel(description = "status represents the current information of a snapshot.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T07:16:21.651588Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1VolumeSnapshotContentStatus {
  public static final String SERIALIZED_NAME_CREATION_TIME = "creationTime";
  @SerializedName(SERIALIZED_NAME_CREATION_TIME)
  private Long creationTime;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private V1VolumeSnapshotContentStatusError error;

  public static final String SERIALIZED_NAME_READY_TO_USE = "readyToUse";
  @SerializedName(SERIALIZED_NAME_READY_TO_USE)
  private Boolean readyToUse;

  public static final String SERIALIZED_NAME_RESTORE_SIZE = "restoreSize";
  @SerializedName(SERIALIZED_NAME_RESTORE_SIZE)
  private Long restoreSize;

  public static final String SERIALIZED_NAME_SNAPSHOT_HANDLE = "snapshotHandle";
  @SerializedName(SERIALIZED_NAME_SNAPSHOT_HANDLE)
  private String snapshotHandle;

  public static final String SERIALIZED_NAME_VOLUME_GROUP_SNAPSHOT_HANDLE = "volumeGroupSnapshotHandle";
  @SerializedName(SERIALIZED_NAME_VOLUME_GROUP_SNAPSHOT_HANDLE)
  private String volumeGroupSnapshotHandle;

  public V1VolumeSnapshotContentStatus() {
  }

  public V1VolumeSnapshotContentStatus creationTime(Long creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * creationTime is the timestamp when the point-in-time snapshot is taken by the underlying storage system. In dynamic snapshot creation case, this field will be filled in by the CSI snapshotter sidecar with the \&quot;creation_time\&quot; value returned from CSI \&quot;CreateSnapshot\&quot; gRPC call. For a pre-existing snapshot, this field will be filled with the \&quot;creation_time\&quot; value returned from the CSI \&quot;ListSnapshots\&quot; gRPC call if the driver supports it. If not specified, it indicates the creation time is unknown. The format of this field is a Unix nanoseconds time encoded as an int64. On Unix, the command &#x60;date +%s%N&#x60; returns the current time in nanoseconds since 1970-01-01 00:00:00 UTC.
   * @return creationTime
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "creationTime is the timestamp when the point-in-time snapshot is taken by the underlying storage system. In dynamic snapshot creation case, this field will be filled in by the CSI snapshotter sidecar with the \"creation_time\" value returned from CSI \"CreateSnapshot\" gRPC call. For a pre-existing snapshot, this field will be filled with the \"creation_time\" value returned from the CSI \"ListSnapshots\" gRPC call if the driver supports it. If not specified, it indicates the creation time is unknown. The format of this field is a Unix nanoseconds time encoded as an int64. On Unix, the command `date +%s%N` returns the current time in nanoseconds since 1970-01-01 00:00:00 UTC.")
  public Long getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(Long creationTime) {
    this.creationTime = creationTime;
  }


  public V1VolumeSnapshotContentStatus error(V1VolumeSnapshotContentStatusError error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1VolumeSnapshotContentStatusError getError() {
    return error;
  }

  public void setError(V1VolumeSnapshotContentStatusError error) {
    this.error = error;
  }


  public V1VolumeSnapshotContentStatus readyToUse(Boolean readyToUse) {
    this.readyToUse = readyToUse;
    return this;
  }

   /**
   * readyToUse indicates if a snapshot is ready to be used to restore a volume. In dynamic snapshot creation case, this field will be filled in by the CSI snapshotter sidecar with the \&quot;ready_to_use\&quot; value returned from CSI \&quot;CreateSnapshot\&quot; gRPC call. For a pre-existing snapshot, this field will be filled with the \&quot;ready_to_use\&quot; value returned from the CSI \&quot;ListSnapshots\&quot; gRPC call if the driver supports it, otherwise, this field will be set to \&quot;True\&quot;. If not specified, it means the readiness of a snapshot is unknown.
   * @return readyToUse
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "readyToUse indicates if a snapshot is ready to be used to restore a volume. In dynamic snapshot creation case, this field will be filled in by the CSI snapshotter sidecar with the \"ready_to_use\" value returned from CSI \"CreateSnapshot\" gRPC call. For a pre-existing snapshot, this field will be filled with the \"ready_to_use\" value returned from the CSI \"ListSnapshots\" gRPC call if the driver supports it, otherwise, this field will be set to \"True\". If not specified, it means the readiness of a snapshot is unknown.")
  public Boolean getReadyToUse() {
    return readyToUse;
  }

  public void setReadyToUse(Boolean readyToUse) {
    this.readyToUse = readyToUse;
  }


  public V1VolumeSnapshotContentStatus restoreSize(Long restoreSize) {
    this.restoreSize = restoreSize;
    return this;
  }

   /**
   * restoreSize represents the complete size of the snapshot in bytes. In dynamic snapshot creation case, this field will be filled in by the CSI snapshotter sidecar with the \&quot;size_bytes\&quot; value returned from CSI \&quot;CreateSnapshot\&quot; gRPC call. For a pre-existing snapshot, this field will be filled with the \&quot;size_bytes\&quot; value returned from the CSI \&quot;ListSnapshots\&quot; gRPC call if the driver supports it. When restoring a volume from this snapshot, the size of the volume MUST NOT be smaller than the restoreSize if it is specified, otherwise the restoration will fail. If not specified, it indicates that the size is unknown.
   * minimum: 0
   * @return restoreSize
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "restoreSize represents the complete size of the snapshot in bytes. In dynamic snapshot creation case, this field will be filled in by the CSI snapshotter sidecar with the \"size_bytes\" value returned from CSI \"CreateSnapshot\" gRPC call. For a pre-existing snapshot, this field will be filled with the \"size_bytes\" value returned from the CSI \"ListSnapshots\" gRPC call if the driver supports it. When restoring a volume from this snapshot, the size of the volume MUST NOT be smaller than the restoreSize if it is specified, otherwise the restoration will fail. If not specified, it indicates that the size is unknown.")
  public Long getRestoreSize() {
    return restoreSize;
  }

  public void setRestoreSize(Long restoreSize) {
    this.restoreSize = restoreSize;
  }


  public V1VolumeSnapshotContentStatus snapshotHandle(String snapshotHandle) {
    this.snapshotHandle = snapshotHandle;
    return this;
  }

   /**
   * snapshotHandle is the CSI \&quot;snapshot_id\&quot; of a snapshot on the underlying storage system. If not specified, it indicates that dynamic snapshot creation has either failed or it is still in progress.
   * @return snapshotHandle
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "snapshotHandle is the CSI \"snapshot_id\" of a snapshot on the underlying storage system. If not specified, it indicates that dynamic snapshot creation has either failed or it is still in progress.")
  public String getSnapshotHandle() {
    return snapshotHandle;
  }

  public void setSnapshotHandle(String snapshotHandle) {
    this.snapshotHandle = snapshotHandle;
  }


  public V1VolumeSnapshotContentStatus volumeGroupSnapshotHandle(String volumeGroupSnapshotHandle) {
    this.volumeGroupSnapshotHandle = volumeGroupSnapshotHandle;
    return this;
  }

   /**
   * VolumeGroupSnapshotHandle is the CSI \&quot;group_snapshot_id\&quot; of a group snapshot on the underlying storage system.
   * @return volumeGroupSnapshotHandle
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "VolumeGroupSnapshotHandle is the CSI \"group_snapshot_id\" of a group snapshot on the underlying storage system.")
  public String getVolumeGroupSnapshotHandle() {
    return volumeGroupSnapshotHandle;
  }

  public void setVolumeGroupSnapshotHandle(String volumeGroupSnapshotHandle) {
    this.volumeGroupSnapshotHandle = volumeGroupSnapshotHandle;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1VolumeSnapshotContentStatus v1VolumeSnapshotContentStatus = (V1VolumeSnapshotContentStatus) o;
    return Objects.equals(this.creationTime, v1VolumeSnapshotContentStatus.creationTime) &&
        Objects.equals(this.error, v1VolumeSnapshotContentStatus.error) &&
        Objects.equals(this.readyToUse, v1VolumeSnapshotContentStatus.readyToUse) &&
        Objects.equals(this.restoreSize, v1VolumeSnapshotContentStatus.restoreSize) &&
        Objects.equals(this.snapshotHandle, v1VolumeSnapshotContentStatus.snapshotHandle) &&
        Objects.equals(this.volumeGroupSnapshotHandle, v1VolumeSnapshotContentStatus.volumeGroupSnapshotHandle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationTime, error, readyToUse, restoreSize, snapshotHandle, volumeGroupSnapshotHandle);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1VolumeSnapshotContentStatus {\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    readyToUse: ").append(toIndentedString(readyToUse)).append("\n");
    sb.append("    restoreSize: ").append(toIndentedString(restoreSize)).append("\n");
    sb.append("    snapshotHandle: ").append(toIndentedString(snapshotHandle)).append("\n");
    sb.append("    volumeGroupSnapshotHandle: ").append(toIndentedString(volumeGroupSnapshotHandle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("creationTime");
    openapiFields.add("error");
    openapiFields.add("readyToUse");
    openapiFields.add("restoreSize");
    openapiFields.add("snapshotHandle");
    openapiFields.add("volumeGroupSnapshotHandle");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1VolumeSnapshotContentStatus
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1VolumeSnapshotContentStatus.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1VolumeSnapshotContentStatus is not found in the empty JSON string", V1VolumeSnapshotContentStatus.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1VolumeSnapshotContentStatus.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1VolumeSnapshotContentStatus` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `error`
      if (jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) {
        V1VolumeSnapshotContentStatusError.validateJsonElement(jsonObj.get("error"));
      }
      if ((jsonObj.get("snapshotHandle") != null && !jsonObj.get("snapshotHandle").isJsonNull()) && !jsonObj.get("snapshotHandle").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `snapshotHandle` to be a primitive type in the JSON string but got `%s`", jsonObj.get("snapshotHandle").toString()));
      }
      if ((jsonObj.get("volumeGroupSnapshotHandle") != null && !jsonObj.get("volumeGroupSnapshotHandle").isJsonNull()) && !jsonObj.get("volumeGroupSnapshotHandle").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `volumeGroupSnapshotHandle` to be a primitive type in the JSON string but got `%s`", jsonObj.get("volumeGroupSnapshotHandle").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1VolumeSnapshotContentStatus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1VolumeSnapshotContentStatus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1VolumeSnapshotContentStatus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1VolumeSnapshotContentStatus.class));

       return (TypeAdapter<T>) new TypeAdapter<V1VolumeSnapshotContentStatus>() {
           @Override
           public void write(JsonWriter out, V1VolumeSnapshotContentStatus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1VolumeSnapshotContentStatus read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1VolumeSnapshotContentStatus given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1VolumeSnapshotContentStatus
  * @throws IOException if the JSON string is invalid with respect to V1VolumeSnapshotContentStatus
  */
  public static V1VolumeSnapshotContentStatus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1VolumeSnapshotContentStatus.class);
  }

 /**
  * Convert an instance of V1VolumeSnapshotContentStatus to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

