/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.k8s.storage.snapshot.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.k8s.storage.snapshot.models.V1VolumeSnapshotStatusError;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * status represents the current information of a snapshot. Consumers must verify binding between VolumeSnapshot and VolumeSnapshotContent objects is successful (by validating that both VolumeSnapshot and VolumeSnapshotContent point at each other) before using this object.
 */
@ApiModel(description = "status represents the current information of a snapshot. Consumers must verify binding between VolumeSnapshot and VolumeSnapshotContent objects is successful (by validating that both VolumeSnapshot and VolumeSnapshotContent point at each other) before using this object.")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-07T07:16:21.651588Z[Etc/UTC]", comments = "Generator version: 7.6.0")
public class V1VolumeSnapshotStatus {
  public static final String SERIALIZED_NAME_BOUND_VOLUME_SNAPSHOT_CONTENT_NAME = "boundVolumeSnapshotContentName";
  @SerializedName(SERIALIZED_NAME_BOUND_VOLUME_SNAPSHOT_CONTENT_NAME)
  private String boundVolumeSnapshotContentName;

  public static final String SERIALIZED_NAME_CREATION_TIME = "creationTime";
  @SerializedName(SERIALIZED_NAME_CREATION_TIME)
  private OffsetDateTime creationTime;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private V1VolumeSnapshotStatusError error;

  public static final String SERIALIZED_NAME_READY_TO_USE = "readyToUse";
  @SerializedName(SERIALIZED_NAME_READY_TO_USE)
  private Boolean readyToUse;

  public static final String SERIALIZED_NAME_RESTORE_SIZE = "restoreSize";
  @SerializedName(SERIALIZED_NAME_RESTORE_SIZE)
  private String restoreSize;

  public static final String SERIALIZED_NAME_VOLUME_GROUP_SNAPSHOT_NAME = "volumeGroupSnapshotName";
  @SerializedName(SERIALIZED_NAME_VOLUME_GROUP_SNAPSHOT_NAME)
  private String volumeGroupSnapshotName;

  public V1VolumeSnapshotStatus() {
  }

  public V1VolumeSnapshotStatus boundVolumeSnapshotContentName(String boundVolumeSnapshotContentName) {
    this.boundVolumeSnapshotContentName = boundVolumeSnapshotContentName;
    return this;
  }

   /**
   * boundVolumeSnapshotContentName is the name of the VolumeSnapshotContent object to which this VolumeSnapshot object intends to bind to. If not specified, it indicates that the VolumeSnapshot object has not been successfully bound to a VolumeSnapshotContent object yet. NOTE: To avoid possible security issues, consumers must verify binding between VolumeSnapshot and VolumeSnapshotContent objects is successful (by validating that both VolumeSnapshot and VolumeSnapshotContent point at each other) before using this object.
   * @return boundVolumeSnapshotContentName
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "boundVolumeSnapshotContentName is the name of the VolumeSnapshotContent object to which this VolumeSnapshot object intends to bind to. If not specified, it indicates that the VolumeSnapshot object has not been successfully bound to a VolumeSnapshotContent object yet. NOTE: To avoid possible security issues, consumers must verify binding between VolumeSnapshot and VolumeSnapshotContent objects is successful (by validating that both VolumeSnapshot and VolumeSnapshotContent point at each other) before using this object.")
  public String getBoundVolumeSnapshotContentName() {
    return boundVolumeSnapshotContentName;
  }

  public void setBoundVolumeSnapshotContentName(String boundVolumeSnapshotContentName) {
    this.boundVolumeSnapshotContentName = boundVolumeSnapshotContentName;
  }


  public V1VolumeSnapshotStatus creationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * creationTime is the timestamp when the point-in-time snapshot is taken by the underlying storage system. In dynamic snapshot creation case, this field will be filled in by the snapshot controller with the \&quot;creation_time\&quot; value returned from CSI \&quot;CreateSnapshot\&quot; gRPC call. For a pre-existing snapshot, this field will be filled with the \&quot;creation_time\&quot; value returned from the CSI \&quot;ListSnapshots\&quot; gRPC call if the driver supports it. If not specified, it may indicate that the creation time of the snapshot is unknown.
   * @return creationTime
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "creationTime is the timestamp when the point-in-time snapshot is taken by the underlying storage system. In dynamic snapshot creation case, this field will be filled in by the snapshot controller with the \"creation_time\" value returned from CSI \"CreateSnapshot\" gRPC call. For a pre-existing snapshot, this field will be filled with the \"creation_time\" value returned from the CSI \"ListSnapshots\" gRPC call if the driver supports it. If not specified, it may indicate that the creation time of the snapshot is unknown.")
  public OffsetDateTime getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
  }


  public V1VolumeSnapshotStatus error(V1VolumeSnapshotStatusError error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  public V1VolumeSnapshotStatusError getError() {
    return error;
  }

  public void setError(V1VolumeSnapshotStatusError error) {
    this.error = error;
  }


  public V1VolumeSnapshotStatus readyToUse(Boolean readyToUse) {
    this.readyToUse = readyToUse;
    return this;
  }

   /**
   * readyToUse indicates if the snapshot is ready to be used to restore a volume. In dynamic snapshot creation case, this field will be filled in by the snapshot controller with the \&quot;ready_to_use\&quot; value returned from CSI \&quot;CreateSnapshot\&quot; gRPC call. For a pre-existing snapshot, this field will be filled with the \&quot;ready_to_use\&quot; value returned from the CSI \&quot;ListSnapshots\&quot; gRPC call if the driver supports it, otherwise, this field will be set to \&quot;True\&quot;. If not specified, it means the readiness of a snapshot is unknown.
   * @return readyToUse
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "readyToUse indicates if the snapshot is ready to be used to restore a volume. In dynamic snapshot creation case, this field will be filled in by the snapshot controller with the \"ready_to_use\" value returned from CSI \"CreateSnapshot\" gRPC call. For a pre-existing snapshot, this field will be filled with the \"ready_to_use\" value returned from the CSI \"ListSnapshots\" gRPC call if the driver supports it, otherwise, this field will be set to \"True\". If not specified, it means the readiness of a snapshot is unknown.")
  public Boolean getReadyToUse() {
    return readyToUse;
  }

  public void setReadyToUse(Boolean readyToUse) {
    this.readyToUse = readyToUse;
  }


  public V1VolumeSnapshotStatus restoreSize(String restoreSize) {
    this.restoreSize = restoreSize;
    return this;
  }

   /**
   * restoreSize represents the minimum size of volume required to create a volume from this snapshot. In dynamic snapshot creation case, this field will be filled in by the snapshot controller with the \&quot;size_bytes\&quot; value returned from CSI \&quot;CreateSnapshot\&quot; gRPC call. For a pre-existing snapshot, this field will be filled with the \&quot;size_bytes\&quot; value returned from the CSI \&quot;ListSnapshots\&quot; gRPC call if the driver supports it. When restoring a volume from this snapshot, the size of the volume MUST NOT be smaller than the restoreSize if it is specified, otherwise the restoration will fail. If not specified, it indicates that the size is unknown.
   * @return restoreSize
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "restoreSize represents the minimum size of volume required to create a volume from this snapshot. In dynamic snapshot creation case, this field will be filled in by the snapshot controller with the \"size_bytes\" value returned from CSI \"CreateSnapshot\" gRPC call. For a pre-existing snapshot, this field will be filled with the \"size_bytes\" value returned from the CSI \"ListSnapshots\" gRPC call if the driver supports it. When restoring a volume from this snapshot, the size of the volume MUST NOT be smaller than the restoreSize if it is specified, otherwise the restoration will fail. If not specified, it indicates that the size is unknown.")
  public String getRestoreSize() {
    return restoreSize;
  }

  public void setRestoreSize(String restoreSize) {
    this.restoreSize = restoreSize;
  }


  public V1VolumeSnapshotStatus volumeGroupSnapshotName(String volumeGroupSnapshotName) {
    this.volumeGroupSnapshotName = volumeGroupSnapshotName;
    return this;
  }

   /**
   * VolumeGroupSnapshotName is the name of the VolumeGroupSnapshot of which this VolumeSnapshot is a part of.
   * @return volumeGroupSnapshotName
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "VolumeGroupSnapshotName is the name of the VolumeGroupSnapshot of which this VolumeSnapshot is a part of.")
  public String getVolumeGroupSnapshotName() {
    return volumeGroupSnapshotName;
  }

  public void setVolumeGroupSnapshotName(String volumeGroupSnapshotName) {
    this.volumeGroupSnapshotName = volumeGroupSnapshotName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1VolumeSnapshotStatus v1VolumeSnapshotStatus = (V1VolumeSnapshotStatus) o;
    return Objects.equals(this.boundVolumeSnapshotContentName, v1VolumeSnapshotStatus.boundVolumeSnapshotContentName) &&
        Objects.equals(this.creationTime, v1VolumeSnapshotStatus.creationTime) &&
        Objects.equals(this.error, v1VolumeSnapshotStatus.error) &&
        Objects.equals(this.readyToUse, v1VolumeSnapshotStatus.readyToUse) &&
        Objects.equals(this.restoreSize, v1VolumeSnapshotStatus.restoreSize) &&
        Objects.equals(this.volumeGroupSnapshotName, v1VolumeSnapshotStatus.volumeGroupSnapshotName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(boundVolumeSnapshotContentName, creationTime, error, readyToUse, restoreSize, volumeGroupSnapshotName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1VolumeSnapshotStatus {\n");
    sb.append("    boundVolumeSnapshotContentName: ").append(toIndentedString(boundVolumeSnapshotContentName)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    readyToUse: ").append(toIndentedString(readyToUse)).append("\n");
    sb.append("    restoreSize: ").append(toIndentedString(restoreSize)).append("\n");
    sb.append("    volumeGroupSnapshotName: ").append(toIndentedString(volumeGroupSnapshotName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("boundVolumeSnapshotContentName");
    openapiFields.add("creationTime");
    openapiFields.add("error");
    openapiFields.add("readyToUse");
    openapiFields.add("restoreSize");
    openapiFields.add("volumeGroupSnapshotName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1VolumeSnapshotStatus
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1VolumeSnapshotStatus.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1VolumeSnapshotStatus is not found in the empty JSON string", V1VolumeSnapshotStatus.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1VolumeSnapshotStatus.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1VolumeSnapshotStatus` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("boundVolumeSnapshotContentName") != null && !jsonObj.get("boundVolumeSnapshotContentName").isJsonNull()) && !jsonObj.get("boundVolumeSnapshotContentName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `boundVolumeSnapshotContentName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("boundVolumeSnapshotContentName").toString()));
      }
      // validate the optional field `error`
      if (jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) {
        V1VolumeSnapshotStatusError.validateJsonElement(jsonObj.get("error"));
      }
      if ((jsonObj.get("restoreSize") != null && !jsonObj.get("restoreSize").isJsonNull()) && !jsonObj.get("restoreSize").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `restoreSize` to be a primitive type in the JSON string but got `%s`", jsonObj.get("restoreSize").toString()));
      }
      if ((jsonObj.get("volumeGroupSnapshotName") != null && !jsonObj.get("volumeGroupSnapshotName").isJsonNull()) && !jsonObj.get("volumeGroupSnapshotName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `volumeGroupSnapshotName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("volumeGroupSnapshotName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1VolumeSnapshotStatus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1VolumeSnapshotStatus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1VolumeSnapshotStatus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1VolumeSnapshotStatus.class));

       return (TypeAdapter<T>) new TypeAdapter<V1VolumeSnapshotStatus>() {
           @Override
           public void write(JsonWriter out, V1VolumeSnapshotStatus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1VolumeSnapshotStatus read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1VolumeSnapshotStatus given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1VolumeSnapshotStatus
  * @throws IOException if the JSON string is invalid with respect to V1VolumeSnapshotStatus
  */
  public static V1VolumeSnapshotStatus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1VolumeSnapshotStatus.class);
  }

 /**
  * Convert an instance of V1VolumeSnapshotStatus to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

